---
title: "Learning (not) to Trade"
author: "Java"
output:
  pdf_document:
    keep_tex: yes
    includes:
      in_header: diss.sty
  html_notebook: default
  html_document: default
  word_document: default
---

```{r echo = F, results="hide", warning=F, message=F}
library(magrittr)

knitr::opts_chunk$set(
  # dev='tikz', 
  echo = F, cache = F, eval = F, message = F, warning = F,
                      fig.path = '../../../../../Dropbox/LearningToTrade/figure/')

datapath = './data/'
```

```{r dev = 'tikz', ExitTS, eval=T}
load('ExitTSplot.rda' %>% paste0(datapath, .))
replayPlot(ExitTS1)
replayPlot(ExitTS2)
replayPlot(ExitTS3)
```

```{r dev = 'tikz', logreturnTS, eval=F}
load('logreturnTS.rda' %>% paste0(datapath, .))
replayPlot(logreturnTS)
```

```{r dev = 'tikz', returnTS, eval=F}
load('returnTS.rda' %>% paste0(datapath, .))
replayPlot(AvgReturnTS)
replayPlot(AvgReturnTSdemean)
```

```{r dev = 'tikz', ReturnbyAgeExit, eval=F}
load('ReturnbyAgeExit.rda' %>% paste0(datapath, .))
replayPlot(ReturnbyAgeExit1)
replayPlot(ReturnbyAgeExit2)
replayPlot(ReturnbyAgeExit3)
replayPlot(ReturnbyAgeExitdemean1)
replayPlot(ReturnbyAgeExitdemean2)
replayPlot(ReturnbyAgeExitdemean3)
```

```{r dev = 'tikz', trreturnquantile, eval=F}
load('trreturnquantile.rda' %>% paste0(datapath, .))
replayPlot(trreturnquantile)
```

```{r ExitTSthird, eval=F}
load('ExitTSthird.rda')
replayPlot(ExitTSthird1)
replayPlot(ExitTSthird2)
replayPlot(ExitTSthird3)
```

```{r AvgReturnByAge, eval=F}
load('AvgReturnByAge.rda')
replayPlot(AvgYearReturn)
replayPlot(AvgYearReturnNorm)
replayPlot(AvgCumReturn)
replayPlot(AvgCumReturnNorm)
```

```{r rouentry, eval=F}
load('rouentry.rda')
replayPlot(rouentry)
replayPlot(no_traders)
replayPlot(no_traderswt)
```

```{r massbyage, eval=F}
load('massbyage.rda')
replayPlot(massbyage)
```

```{r massdist, eval=F}
load('massdist.rda')
replayPlot(massdist)
replayPlot(massdistwt)
replayPlot(massexitdist)
replayPlot(exitlikelidist)
```

```{r pltexit, eval=F}
load('pltexitgivenRT.rda')
replayPlot(pltexitgivenRT1)
replayPlot(pltexitgivenRT2)
replayPlot(pltexitgivenRT3)
```

```{r pltexitgivenT, eval=F}
load('pltexitgivenT.rda')
replayPlot(pltexitgivenageT1)
replayPlot(pltexitgivenageT2)
replayPlot(pltexitgivenageT3)
```

```{r rtn, eval=F}
load('avgreturn365.rda')
# replayPlot(avgreturn548)
# replayPlot(avgreturn183)
replayPlot(avgreturn365)
```  

```{r trreturncum, eval=F}
load('trreturncum.rda')
replayPlot(trreturncum)
load('trreturn.rda')
replayPlot(trreturn)
load('trreturn46.rda')
replayPlot(trreturn46)
```  

```{r trreturn, eval=F}
load('trreturn.rda')
replayPlot(trreturn183)
replayPlot(trreturn365)
```  

```{r trintfolonecohort, eval=F}
load('trintfolonecohort.rda')
replayPlot(trintchf1)
replayPlot(trintchf2)
replayPlot(trintchf3)
replayPlot(trintcnt1)
replayPlot(trintcnt2)
replayPlot(trintcnt3)
```