---
title: "Learning (not) to Trade"
author: "Java"
output:
  pdf_document:
    keep_tex: yes
    includes:
      in_header: diss.sty
  html_notebook: default
  html_document: default
  word_document: default
---

```{r echo = F, results='hide', warning=F, message=F}
library(data.table)
library(tidyr)
library(lubridate)
library(lattice)
library(openintro)
library(zoo)
library(pracma)
library(nloptr)
library(speedglm)
library(timeDate)
library(spatstat)
library(ggplot2)
library(gridExtra)
library(dplyr)
library(magrittr)
library(survival)
library(plm)
library(pglm)
library(Rchoice)
library(parallel)

knitr::opts_chunk$set(dev='tikz', echo = F, cache = F, eval = F, message = F, warning = F)

options(stringsAsFactors = F,
        datatable.WhenJisSymbolThenCallingScope = T)
```

```{r include = F, eval = T, echo = F}
datapath = './data/'
```

```{r loadmiscdata, include = F, eval = F, echo = F}
### insiders
insiders = fread('insiders_accounts.txt' %>% paste0(datapath, .),
                 sep = ";", header = T, col.names = c(
  "client", "attr_id", "attr_val"))


### personas info
persID = fread('persons_accounts.txt' %>% paste0(datapath, .),
                 sep = ";", header = T, col.names = c(
  "account_id", "person_id", "title_label", "birth_year", "language", "numbered", "company_flag")) # we do not use person_id in the end because some people use different trading strategies for different account anyway.


### type of accounts
acc_types = fread('accounts_types.txt' %>% paste0(datapath, .),
                 sep = ";", header = T, col.names = c(
  "client", "attr_id", "attr_val"))


### Retail and large private accounts, trading accounts, and swissquote label
Tab4ext = fread('Tab4_extended.txt' %>% paste0(datapath, .),
                 sep = ";", header = T, col.names = c(
  "account_id", "client",  "mark_camp", "age", "country_res",
  "client_segm", "brand_id","brand_lab", "acc_type_id", "acc_type",
  "status",  "status_val", "acc_status_date"))


Tab4ext[, ':='(
  acc_status_date = fast_strptime(acc_status_date, "%Y-%m-%d") %>% as.Date
)]
# 1000 times faster than Tab4ext$acc_status_date %<>% as.Date

### Maybe we should consider deleting HNW accounts?
Tab4ext$acc_status_date %<>% as.Date
Tab4ext %<>% setorder('client') %>% .[brand_lab=='Swissquote' & acc_type=='Trading'] %>%
  .[client_segm %in% c("HNW accounts", "Retail account")] 

last_close = Tab4ext[status_val == 'Closed',list(last_close=max(acc_status_date, na.rm = T)),by='client']
last_open = Tab4ext[status_val == 'Open',list(last_open=max(acc_status_date, na.rm = T)),by='client']

Closed_account = merge(last_close,last_open,all = T)
Closed_account$closing_date = ifelse(Closed_account$last_open < Closed_account$last_close, Closed_account$last_close, NA) %>% as.Date

### Clients: (retail accounts, large private accounts, Swissquote label, direct accounts, no insiders)
cl_retail = unique(Tab4ext$client)  %>%  .[!(. %in% insiders$client)] %>% 
  .[(. %in% acc_types$client[acc_types$attr_val=='Direct client'])]

save(insiders, file = 'insiders.rda' %>% paste0(datapath, .))
save(persID, file = 'persID.rda' %>% paste0(datapath, .))
save(acc_types, file = 'acc_types.rda' %>% paste0(datapath, .))
save(Tab4ext, file = 'Tab4ext.rda' %>% paste0(datapath, .))
save(Closed_account, file = 'Closed_account.rda' %>% paste0(datapath, .))
save(cl_retail, file = 'cl_retail.rda' %>% paste0(datapath, .))
```

```{r sty, include = F, eval = F, echo = F}
sty = fread('securities.txt'%>% paste0(datapath, .),
                 sep = ';', header = T, col.names = c(
  "sec_id", "name","sec_type","sec_group", "asset_type", "symbol","isin","stock_exchange", "cur","strike","maturity","contractsize","call_put","cotation_type", "cotation_factor", "underlying","underlying_id","top"
  ))  %>% .[,isin:=substr(isin,1,12)] %>%
  .[,security_key := paste0(isin, "_", stock_exchange, "_", cur)]
save(sty, file = 'sty.rda' %>% paste0(datapath, .))
```

```{r loaddata, include = F, eval = F, echo = F}
load('utrans_2001_2018.rda' %>% paste0(datapath, .))
optiontaders = u.trans[asset_type %in% c(67, 68), client] %>% unique

gc()

load('sty.rda' %>% paste0(datapath, .))
load('cl_retail.rda' %>% paste0(datapath, .))

### only buy, sell and dividents
u.trans2 = u.trans[client %in% cl_retail & 
                     action %in% c('B','S','D', # lowercases are different actions. do not convert to uppercase
                                   'A', # transfer securities in 
                                   'C' # transfer securities out
                                   ) & 
                     security_key %in% sty$security_key[(sty$asset_type %in% c(30:32))]]

u.trans2 = u.trans2[order(client, date_trans)]
actions = u.trans2[, list(
  first_act = action[1],
  last_act = tail(action,1)
  ), by = client]
cl_transferin = actions[first_act == 'A']$client
cl_transferout = actions[last_act == 'C']$client
gc()


u.trans2[, ':='(
  action = as.character(action),
  symbol = as.character(symbol),
  cur = as.character(cur),
  isin = as.character(isin)
)]

#u.trans=u.trans[!duplicated(u.trans[,c('trade_id','client','date_trans','isin')])] #%>%.[asset_type %in% c(30, 31, 32)]

save(u.trans2, file = 'u.trans2.rda' %>% paste0(datapath, .))
save(optiontaders, file = 'optiontaders.rda' %>% paste0(datapath, .))
save(cl_transferin, cl_transferout, file = 'cl_transferin.rda' %>% paste0(datapath, .))
```

```{r utrans, eval=F}
load('u.trans2.rda' %>% paste0(datapath, .))
u.trans2[, ':='(
  trade_id = NULL,
  symbol = NULL,
  asset_type = NULL,
  stock_exchange = NULL,
  isin = NULL
)]

## number of securities traded
nsec = u.trans2[, c('client','security_key')] %>% unique %>% .$client %>% table

## number of trades
ntrade = u.trans2[, 'client'] %>% table

## last seen trade
last_trade = u.trans2[,list(last_tr=max(date_trans, na.rm = T)),by='client']
first_trade = u.trans2[,list(first_tr=min(date_trans, na.rm = T)),by='client'] 

save(nsec, file = 'nsec.rda' %>% paste0(datapath, .))
save(ntrade, file = 'ntrade.rda' %>% paste0(datapath, .))
save(last_trade, file = 'last_trade.rda' %>% paste0(datapath, .))
save(first_trade, file = 'first_trade.rda' %>% paste0(datapath, .))
```

```{r eval=F}
# account value should not preceed account open date? 
load('Tab4ext.rda' %>% paste0(datapath, .))
gc()
# need clientdaily since 2001?
clientdaily = readRDS('clientdaily.Rds' %>% paste0(datapath, .))
gc()
SMI = clientdaily[, c('account_date', 'smidailyret')] %>% unique
SMI = merge(data.table(account_date = seq.Date(as.Date('2009-01-01'), as.Date('2018-12-28'), 1)), SMI, by = 'account_date', all = T)[order(account_date)]
SMI[, smi365 := rollsum(smidailyret, 365, align = 'right', na.rm = T, fill = NA)]
save(SMI, file = 'SMI.rda' %>% paste0(datapath, .))

acct_start = merge(
  Tab4ext[status_val == 'Open',list(first_open=min(acc_status_date, na.rm = T)),by= client],
  clientdaily[, list(fist_status=min(account_date)), by = client]
  , by = 'client', all = T)

# `(acct_start$first_open - acct_start$fist_status >0) %>% which = integer(0)` so the next step does not matter that much -- we will always use first_open as acct_start
acct_start[, acct_start:=pmin(first_open, fist_status, na.rm = T)]

load('Closed_account.rda' %>% paste0(datapath, .))
Closed_account %<>% merge(
  clientdaily[, list(last_status=max(account_date)), by = client]
  , by = 'client', all = T)

# after spot checking, lest_status sometimes exceeds closing_date, which shouldn't have happened. We should use closing_date, and ignore records afterwards because those closed accounts' records appear inactive, becuase `(Tab4_lt$last_tr-Tab4_lt$closing_date >0) %>% which = integer(0)`
# Closed_account[, check:= closing_date - last_status]


load('last_trade.rda' %>% paste0(datapath, .))
load('first_trade.rda' %>% paste0(datapath, .))

Tab4_lt = merge(first_trade,last_trade,all.x = T) %>% 
  merge(Closed_account,all.x = T) %>% merge(acct_start, all.x = T)

# attention --- first trade "A", magnitude, big transfer means history with other banks
# for age and gender 
load('persID.rda' %>% paste0(datapath, .))
pers = merge(persID[,c("account_id","birth_year",'title_label')],Tab4ext[,c("account_id","client", 'country_res')] %>% unique) %>% .[client %in% Tab4_lt$client]
pers$gender = pers$title_label != 'Mr'

# If last trade occurred after the recorded closing date, then use last trade date as closing date
Tab4_lt$check = Tab4_lt$closing_date < Tab4_lt$last_tr
Tab4_lt$closing_date[which(Tab4_lt$check)] = Tab4_lt$last_tr[which(Tab4_lt$check)]


regtable = merge(pers, Tab4_lt[,c('client','first_tr', 'last_tr', 'acct_start','closing_date')], by = 'client')

load('optiontaders.rda' %>% paste0(datapath, .))
regtable[, ':='(firstobs = pmin(acct_start,first_tr, na.rm = T),
                lastobs = ifelse(is.na(closing_date), last_tr, closing_date) %>% as.Date,
                TradesOptions = as.numeric(client %in% optiontaders),
                uncensored = ifelse(is.na(closing_date) , 0,1)
                )][, ':='(
                  actualby = ifelse(  # actual birthyear
                  firstobs %>% format('%Y') %>% as.numeric - birth_year > 12 & birth_year > 1900,
                  birth_year, NA)
                )][, ':='(bioage = 2018 - actualby, 
                          enterage = as.numeric(format(firstobs,'%Y')) - actualby,
                          lifetime = difftime(lastobs, firstobs, units = 'days')+0.25)]


save(regtable, file = 'regtable.rda' %>% paste0(datapath, .))
```

```{r eval=F}
gc()
if(!exists('clientdaily')){
  clientdaily = readRDS('clientdaily.Rds' %>% paste0(datapath, .))
  }
gc()

clientdailycli = unique(clientdaily$client)
mindate = min(clientdaily$account_date, na.rm=T)

# add missing dates
load('regtable.rda' %>% paste0(datapath, .))
clientdays = regtable[client %in% clientdailycli & lifetime > 365 & lastobs > mindate + 365, 
                      list(
  account_date = seq.Date(from = max(firstobs, mindate), to = lastobs, by = 1)
  ), by = client]

gc()
clientdaily365 = merge(clientdaily[, c('client', 'account_date', 'daily_perf')], clientdays, 
                       all.y = T, by = c('client', 'account_date'))
gc()

clientdaily365 = merge(clientdaily365, regtable[,c('client', 'closing_date','firstobs', 'lastobs')], by = 'client', all.x = T)[order(account_date)]
clientdaily365[,':='(age = account_date - firstobs)]

# removing beforehand instead of using na.rm afterwards would massively increase speed!!!
clientdaily365[, daily_perfnaremove := ifelse(is.finite(daily_perf), daily_perf, 0)]
# clientdaily365[, ':='(nclient = .N), by=client]

clientdaily365[, rreturn365 := rollsum(
                daily_perfnaremove, 365, na.rm = T, align = 'right', fill = NA
                ), by = client]

clientdaily365[, ':='(daily_perfnaremove = NULL, daily_perf = NULL)]

saveRDS(clientdaily365, file = 'clientdaily365.rds' %>% paste0(datapath, .))
```

```{r coxre, eval=T}
if(!(exists('clientdaily2')|exists('clientdaily'))){
clientdaily = readRDS('clientdaily365.Rds' %>% paste0(datapath, .))}

xx = clientdaily[is.finite(rreturn365)] %>% merge(regtable[,c('client', 'enterage', 'TradesOptions', 'gender')])
xx[, ':='(
  retpr = ecdf(rreturn365)(rreturn365)), by = account_date][, ':='(
    retprind = ecdf(retpr)(retpr),
    retind = ecdf(rreturn365)(rreturn365)), by = client]

## important: People exit both when return is high and when return is low… but model does not predict that so whatever..
# xx[account_date == closing_date & age > 365.2425 * 3, retprind %>% density(cut = 0) %>% plot]
# xx[account_date == closing_date & age < 365.2425 * 3, retprind %>% density(cut = 0) %>% lines(col='red')]


sumtbl = function(ans){
  temp = ans$coefficients[, c('Estimate', 'Pr(>|t|)')] %>% as.data.table(keep.rownames=T)
  names(temp)[3] = 'pv'
  temp[, ':='(p = paste0("'(", round(pv,3) %>% format(nsmall = 3), ')'),
              str = funcstar(pv))]
  nr = nrow(temp)
  tbl = data.table(rn = rep('', 2*nr+2))
  tbl[seq(1,nr*2,2), 'rn'] = temp$rn
  tbl[seq(2,nr*2,2), 'rn'] = temp$rn %>% paste0('p')
  tbl[seq(2,nr*2,2), 'beta'] = temp$p
  tbl[seq(1,nr*2,2), 'beta'] = temp$Estimate
  tbl$str = ''
  tbl[seq(1,nr*2,2), 'str'] = temp$str
  tbl[nr*2+1, 1] = 'R2'
  tbl[nr*2+1, 2] = ans$r.squared
  tbl[nr*2+2, 1] = 'n'
  tbl[nr*2+2, 2] = ans$residuals %>% length
  return(tbl)
  }

tbl = data.table(rn = '')

retproxy = 'retpr'

n=0
xx[account_date == closing_date, lm(get(retproxy) ~ age)] %>% summary() -> ans
tbl %<>% merge(sumtbl(ans), by = 'rn', all = T, sort = F, suffixes = n:(n+1))
n = n+2

xx[account_date == closing_date, lm(get(retproxy) ~ age + gender)] %>% summary() -> ans
tbl %<>% merge(sumtbl(ans), by = 'rn', all = T, sort = F, suffixes = n:(n+1))
n = n+2

xx[account_date == closing_date, lm(get(retproxy) ~ age + enterage)] %>% summary() -> ans
tbl %<>% merge(sumtbl(ans), by = 'rn', all = T, sort = F, suffixes = n:(n+1))
n = n+2

xx[account_date == closing_date, lm(get(retproxy) ~ age + TradesOptions)] %>% summary() -> ans
tbl %<>% merge(sumtbl(ans), by = 'rn', all = T, sort = F, suffixes = n:(n+1))
n = n+2

xx[account_date == closing_date, lm(get(retproxy) ~ age + gender + enterage + TradesOptions)] %>% summary() -> ans
tbl %<>% merge(sumtbl(ans), by = 'rn', all = T, sort = F, suffixes = n:(n+1))
n = n+2

write.csv(tbl, file='tbl.csv')


xx[account_date == closing_date & age < 365.2425 * 3, lm(retprind ~ age)] %>% summary() -> ans
tbl %<>% merge(sumtbl(ans), by = 'rn', all = T, sort = F, suffixes = n:(n+1))
n = n+2

xx[account_date == closing_date & age < 365.2425 * 3, lm(retprind ~ age + gender + enterage + TradesOptions)] %>% summary() -> ans
tbl %<>% merge(sumtbl(ans), by = 'rn', all = T, sort = F, suffixes = n:(n+1))
n = n+2

xx[account_date == closing_date & age >= 365.2425 * 3, lm(retprind ~ age)] %>% summary() -> ans
tbl %<>% merge(sumtbl(ans), by = 'rn', all = T, sort = F, suffixes = n:(n+1))
n = n+2

xx[account_date == closing_date & age >= 365.2425 * 3, lm(retprind ~ age + gender + enterage + TradesOptions)] %>% summary() -> ans
tbl %<>% merge(sumtbl(ans), by = 'rn', all = T, sort = F, suffixes = n:(n+1))

write.csv(tbl, file='tbl.csv')


xx[account_date == closing_date, lm(retind ~ age)] -> ans
ans$residuals %>% length()
ans %>% summary()
xx[account_date == closing_date, lm(retind ~ age + gender + enterage + TradesOptions)] -> ans
ans$residuals %>% length()
ans %>% summary()

xx[account_date == closing_date & age < 365.2425 * 3, lm(retind ~ age)] -> ans
ans$residuals %>% length()
ans %>% summary()
xx[account_date == closing_date & age < 365.2425 * 3, lm(retind ~ age + gender + enterage + TradesOptions)] -> ans
ans$residuals %>% length()
ans %>% summary()

xx[account_date == closing_date & age >= 365.2425 * 3, lm(retind ~ age)] -> ans
ans$residuals %>% length()
ans %>% summary()
xx[account_date == closing_date & age >= 365.2425 * 3, lm(retind ~ age + gender + enterage + TradesOptions)] -> ans
ans$residuals %>% length()
ans %>% summary()


xx[account_date == closing_date, lm(retpr ~ age)] -> ans
ans$residuals %>% length()
ans %>% summary()
xx[account_date == closing_date, lm(retpr ~ age + gender + enterage + TradesOptions)] -> ans
ans$residuals %>% length()
ans %>% summary()

xx[account_date == closing_date & age < 365.2425 * 3, lm(retpr ~ age)] -> ans
ans$residuals %>% length()
ans %>% summary()
xx[account_date == closing_date & age < 365.2425 * 3, lm(retpr ~ age + gender + enterage + TradesOptions)] -> ans
ans$residuals %>% length()
ans %>% summary()

xx[account_date == closing_date & age >= 365.2425 * 3, lm(retpr ~ age)] -> ans
ans$residuals %>% length()
ans %>% summary()
xx[account_date == closing_date & age >= 365.2425 * 3, lm(retpr ~ age + gender + enterage + TradesOptions)] -> ans
ans$residuals %>% length()
ans %>% summary()


xx[account_date == closing_date, lm(rreturn365 ~ age)] -> ans
ans$residuals %>% length()
ans %>% summary()
xx[account_date == closing_date, lm(rreturn365 ~ age + gender + enterage + TradesOptions)] -> ans
ans$residuals %>% length()
ans %>% summary()

xx[account_date == closing_date & age < 365.2425 * 3, lm(rreturn365 ~ age)] -> ans
ans$residuals %>% length()
ans %>% summary()
xx[account_date == closing_date & age < 365.2425 * 3, lm(rreturn365 ~ age + gender + enterage + TradesOptions)] -> ans
ans$residuals %>% length()
ans %>% summary()

xx[account_date == closing_date & age >= 365.2425 * 3, lm(rreturn365 ~ age)] -> ans
ans$residuals %>% length()
ans %>% summary()
xx[account_date == closing_date & age >= 365.2425 * 3, lm(rreturn365 ~ age + gender + enterage + TradesOptions)] -> ans
ans$residuals %>% length()
ans %>% summary()
```

```{r regress, eval=T}
gc()

xx[account_date < '2018-01-01', ':='(
  ExitNxtYr = ifelse(is.finite(closing_date), (closing_date - account_date) < 365.2425, F))]

library(glmmML)

gc()

aa =  glmmboot(ExitNxtYr ~ age + rreturn365 + gender + enterage + TradesOptions, family=binomial(link="logit"), data=xx[age < 365.2425 *3], cluster=account_date, na.action=na.omit)
aa$n
aa$logLik
summary(aa)

gc()
aa =  glmmboot(ExitNxtYr ~ age + rreturn365 + gender + enterage + TradesOptions, family=binomial(link="logit"), data=xx[age >= 365.2425 *3], cluster=account_date, na.action=na.omit)
aa$n
aa$logLik
summary(aa)

gc()
aa =  glmmboot(ExitNxtYr ~ age + rreturn365 + gender + enterage + TradesOptions, family=binomial(link="logit"), data=xx, cluster=account_date, na.action=na.omit)
aa$n
aa$logLik
summary(aa)



aa = pglm(ExitNxtYr ~ age + rreturn365, data = xx[age < 365.2425 *3], na.action=na.omit, family = binomial(link = 'logit'), index = c('client', 'account_date'), effect = 'time', model=("pooling"))
aa %>% summary

gc()
aa = pglm(ExitNxtYr ~ age + rreturn365, data = xx[age >= 365.2425 *3,], na.action=na.omit, family = binomial('probit'), index = c('client', 'account_date'), effect = 'time', model = "pooling",  method = "bfgs")
aa %>% summary


gc()
time = Sys.time()
xxplmg = plm(rreturn365 ~ age + enterage,
data = xx, index = c('client', 'account_date'), effect = 'twoways')
Sys.time() - time
summary(xxplmg)

rm(xxplmg)
gc()
time = Sys.time()
xxplmg = plm(rreturn365 ~ age + gender + enterage,
data = xx, index = c('client', 'account_date'), effect = 'twoways')
Sys.time() - time
summary(xxplmg)


rm(xxplmg)
gc()
time = Sys.time()
xxplmg = plm(rreturn365 ~ age + TradesOptions,
data = xx, index = c('client', 'account_date'), effect = 'twoways')
Sys.time() - time
summary(xxplmg)

rm(xxplmg)
gc()
time = Sys.time()
xxplmg = plm(rreturn365 ~ age + TradesOptions + nsec + ntrade,
data = xx, index = c('client', 'account_date'), effect = 'twoways')
Sys.time() - time
summary(xxplmg)


rm(xxplmg)
gc()
time = Sys.time()
xxplmg = plm(rreturn365 ~ age + gender + enterage + TradesOptions + nsec + ntrade,
data = xx, index = c('client', 'account_date'), effect = 'twoways')
Sys.time() - time
summary(xxplmg)

# xx = merge(regtable[,c('client', 'firstobs')], clientdaily365[is.finite(rreturn365) & account_date >= '2010-01-01'], by = 'client')
# xx[, age := account_date - firstobs]
# gc()
# save(xx, file = 'tsregressreg.rda')
# 
# 
# 
# xxplmind = plm(rreturn365 ~ age, data = xx, index = c('account_date','client'))
# 
# 
# xxlm = lm(rreturn365 ~ age, data = xx)
# summary(xxlm)
# 
# xxplmind.sum = summary(xxplmind)
# 
# save(xxplmind.sum, file ='xxplmind.sum.rda')
# load('xxplmind.sum.rda')
# 
# 
# 
# xx = xx[,c('client', 'account_date','rreturn365','age')]
# gc()

# # This is identical to xxplmind
# xxplmindtime = plm(rreturn365 ~ age, data = xx, index = c('client', 'account_date'), effect = 'time')
# 
# gc()
# xxplmindtime.sum = summary(xxplmindtime)
# gc()
# 
# save(xxplmindtime.sum, file ='xxplmindtime.sum.rda')

## does not work -- funky coefficient
# xxplmindtw = plm(rreturn365 ~ age, data = xx[client < 210000 & account_date > 2018-06-01], index = c('client', 'account_date'), effect = 'twoways')


load('xxplmindtime.sum.rda')
```