---
title: "Learning (not) to Trade"
author: "Java"
output:
  pdf_document:
    keep_tex: yes
    includes:
      in_header: diss.sty
  html_notebook: default
  html_document: default
  word_document: default
---

```{r echo = F, results="hide", warning=F, message=F}
library(data.table)
library(tidyr)
library(lubridate)
library(lattice)
library(openintro)
library(zoo)
library(pracma)
library(nloptr)
library(speedglm)
library(timeDate)
library(spatstat)
library(ggplot2)
library(gridExtra)
library(dplyr)
library(magrittr)
library(survival)
library(plm)
library(pglm)
library(Rchoice)
library(parallel)

knitr::opts_chunk$set(dev='tikz', echo = F, cache = F, eval = F, message = F, warning = F)

options(stringsAsFactors = F,
        datatable.WhenJisSymbolThenCallingScope = T)

# get_data= function(str){
#   return(get(load(str)))
# }
```

```{r loadmiscdata, include = F, eval = F, echo = F}
sty = fread('securities.txt', sep = ';', header = T, col.names = c(
  "sec_id", "name","sec_type","sec_group", "asset_type", "symbol","isin","stock_exchange", "cur","strike","maturity","contractsize","call_put","cotation_type", "cotation_factor", "underlying","underlying_id","top"
  ))  %>% .[,isin:=substr(isin,1,12)] %>%
  .[,security_key := paste0(isin, "_", stock_exchange, "_", cur)]


### insiders
insiders = fread('insiders_accounts.txt', sep = ";", header = T, col.names = c(
  "client", "attr_id", "attr_val"))


### personas info
persID = fread('persons_accounts.txt', sep = ";", header = T, col.names = c(
  "account_id", "person_id", "title_label", "birth_year", "language", "numbered", "company_flag")) # we do not use person_id in the end because some people use different trading strategies for different account anyway.


### type of accounts
acc_types = fread('accounts_types.txt', sep = ";", header = T, col.names = c(
  "client", "attr_id", "attr_val"))


### Retail and large private accounts, trading accounts, and swissquote label
Tab4ext = fread('Tab4_extended.txt', sep = ";", header = T, col.names = c(
  "account_id", "client",  "mark_camp", "age", "country_res",
                                "client_segm", "brand_id","brand_lab", "acc_type_id", "acc_type",
                                "status",  "status_val", "acc_status_date"))

### Maybe we should consider deleting HNW accounts?
Tab4ext$acc_status_date %<>% as.Date
Tab4ext %<>% setorder('client') %>% .[brand_lab=='Swissquote' & acc_type=='Trading'] %>%
  .[client_segm %in% c("HNW accounts", "Retail account")] 

last_close = Tab4ext[status_val == 'Closed',list(last_close=max(acc_status_date, na.rm = T)),by='client']
last_open = Tab4ext[status_val == 'Open',list(last_open=max(acc_status_date, na.rm = T)),by='client']

Closed_account = merge(last_close,last_open,all = T)
Closed_account$closing_date = ifelse(Closed_account$last_open < Closed_account$last_close, Closed_account$last_close, NA) %>% as.Date

### Clients: (retail accounts, large private accounts, Swissquote label, direct accounts, no insiders)
cl_retail = unique(Tab4ext$client)  %>%  .[!(. %in% insiders$client)] %>% 
  .[(. %in% acc_types$client[acc_types$attr_val=='Direct client'])]

# account_id_retail = unique(Tab4ext$account_id[Tab4ext$client %in% cl_retail])
save(sty, insiders, persID, acc_types, Tab4ext, Closed_account, cl_retail,
     file = 'basicdata.rda')
```

```{r loaddata, include = F, eval = F, echo = F}
load('utrans_2001_2018.rda')
load('basicdata.rda')
load('swiss_mkt_vol_px.rda')
optiontaders = u.trans[asset_type %in% c(67, 68), client] %>% unique

gc()

# u.trans$action %>% table # lowercases are different actions. do not convert to uppercase

### only buy, sell and dividents
u.trans2 = u.trans[client %in% cl_retail & 
                     action %in% c('B','S','D', 
                                   'A', # transfer securities in 
                                   'C' # transfer securities out
                                   ) & 
                     security_key %in% sty$security_key[(sty$asset_type %in% c(30:32))]]

u.trans2 = u.trans2[order(client, date_trans)]
actions = u.trans2[, list(
  first_act = action[1],
  last_act = tail(action,1)
  ), by = client]
cl_transferin = actions[first_act == 'A']$client
cl_transferout = actions[last_act == 'C']$client
gc()

u.trans2$action %<>% as.character
u.trans2$cur %<>% as.character
u.trans2$symbol %<>% as.character
u.trans2$isin %<>% as.character
#u.trans=u.trans[!duplicated(u.trans[,c('trade_id','client','date_trans','isin')])] #%>%.[asset_type %in% c(30, 31, 32)]

save(u.trans2, file = 'u.trans2.rda')
save(optiontaders, file = 'optiontaders.rda')
save(cl_transferin, cl_transferout, file = 'cl_transferin.rda')
```

```{r loadmoredata, eval = F}
load('u.trans2.rda')
load('optiontaders.rda')
load('basicdata.rda')
load('cl_transferin.rda')
gc()
# need clientdaily since 2001?
clientdaily = readRDS('clientdaily.Rds')
gc()
```

```{r eval=F}
u.trans2[, ':='(
  trade_id = NULL,
  symbol = NULL,
  asset_type = NULL,
  stock_exchange = NULL,
  isin = NULL
)]

## number of securities traded
nsec = u.trans2[, c('client','security_key')] %>% unique %>% .$client %>% table

## number of trades
ntrade = u.trans2[, 'client'] %>% table

## average trade per client
meanvol = u.trans2[, list(mean_chf_tr=mean(vol_chf_trans)),by='client']

## last seen trade
last_trade = u.trans2[,list(last_tr=max(date_trans, na.rm = T)),by='client']
first_trade = u.trans2[,list(first_tr=min(date_trans, na.rm = T)),by='client'] 

# account value should not preceed account open date? 
acct_start = merge(
  Tab4ext[status_val == 'Open',list(first_open=min(acc_status_date, na.rm = T)),by= client],
  clientdaily[, list(fist_status=min(account_date)), by = client]
  , by = 'client', all = T)

# `(acct_start$first_open - acct_start$fist_status >0) %>% which = integer(0)` so the next step does not matter that much -- we will always use first_open as acct_start
acct_start[, acct_start:=pmin(first_open, fist_status, na.rm = T)]

Closed_account %<>% merge(
  clientdaily[, list(last_status=max(account_date)), by = client]
  , by = 'client', all = T)

# after spot checking, lest_status sometimes exceeds closing_date, which shouldn't have happened. We should use closing_date, and ignore records afterwards because those closed accounts' records appear inactive, becuase `(Tab4_lt$last_tr-Tab4_lt$closing_date >0) %>% which = integer(0)`
# Closed_account[, check:= closing_date - last_status]


Tab4_lt = merge(first_trade,last_trade,all.x = T) %>% 
  merge(Closed_account,all.x = T) %>% merge(acct_start, all.x = T)

# attention --- first trade "A", magnitude, big transfer means history with other banks
# for age and gender 
pers = merge(persID[,c("account_id","birth_year",'title_label')],Tab4ext[,c("account_id","client", 'country_res')] %>% unique) %>% .[client %in% Tab4_lt$client]
pers$gender = pers$title_label != 'Mr'

# If last trade occurred after the recorded closing date, then use last trade date as closing date
Tab4_lt$check = Tab4_lt$closing_date < Tab4_lt$last_tr
Tab4_lt$closing_date[which(Tab4_lt$check)] = Tab4_lt$last_tr[which(Tab4_lt$check)]


temp = merge(nsec,ntrade, by='.') %>%
  setNames(c('client','nsec','ntrade')) %>%
  merge(meanvol)
temp$client %<>% as.character %>% as.integer
regtable = merge(pers, temp, by = 'client') %>% 
  merge(Tab4_lt[,c('client','first_tr', 'last_tr', 'acct_start','closing_date')], by = 'client')

regtable[, ':='(firstobs = pmin(acct_start,first_tr, na.rm = T),
                lastobs = ifelse(is.na(closing_date), last_tr, closing_date) %>% as.Date,
                TradesOptions = as.numeric(client %in% optiontaders),
                uncensored = ifelse(is.na(closing_date) , 0,1)
                )][, ':='(
                  actualby = ifelse(  # actual birthyear
                  firstobs %>% format('%Y') %>% as.numeric - birth_year > 12 & birth_year > 1900,
                  birth_year, NA)
                )][, ':='(bioage = 2018 - actualby, 
                          enterage = as.numeric(format(firstobs,'%Y')) - actualby,
                          lifetime = difftime(lastobs, firstobs, units = 'days')+0.25)]


save(regtable, file = 'regtable.rda')

gc()
if(!exists('clientdaily')){
  clientdaily = readRDS('clientdaily.Rds')
  }
gc()

clientdailycli = unique(clientdaily$client)

# add missing dates
clientdays = regtable[client %in% clientdailycli, list(
  account_date = seq.Date(from = firstobs, to = lastobs, by = 1)
  ), by = client]

gc()
clientdaily = merge(clientdaily, clientdays, all.y = T, by = c('client', 'account_date'))
gc()

save(clientdaily, file = 'clientdaily2.rda')
```

```{r eval=F}
if(!exists('u.trans2')){load('u.trans2.rda')}
load('regtable.rda')
load('cl_transferin.rda')

u.trans2 = u.trans2[grep('B|S', action)]
trint = merge(u.trans2[!(client %in% cl_transferin), c('client', 'date_trans', 'action', 'vol_chf_trans')],
              regtable[, c('client', 'firstobs', 'closing_date')], by = 'client')

trint[, age:= as.integer(date_trans-firstobs)]

```

```{r eval=T}
cols = c('yellow', 'grey', 'green', 'red')
nrolls = c(183, 365, 548)

# cross sectional regression to get rid of year + individual effect?
 # plm(Ritplus1 ~ YearsTraded + I(YearsTraded^2) + NumSec + NumTrades + PortVal, data = linreg, index = c('yeartrans'), effect = "time")


ctryrs = data.frame(
  min = c(2001, 2001, 2007, 2010),
  max = c(2018, 2006, 2009, 2018)
)

bs = c('B', 'S', 'B|S')

par(mar=c(4,5,1.7,2), mgp = c(2, 0.8, 0))

sigstar = data.frame(thresh=c(0,0.01,0.05,0.1),stars=c('***','**','*',''))

funcstar = function(p){
  ss = p %>% lapply(function(x) which(x>=sigstar[,1]) %>% max %>% sigstar[.,2]) %>% unlist
  ss[is.na(ss)]=''
  ss
}

funks = function(series1,series2){
  p = ks.test(series1, series2)$p
  pf= formatC(p, digits = 3, format = 'f')
  p2 = t.test(series1, series2, na.action=na.omit, alternative = 'two.sided', mu = 0, paired = F, conf.level = 0.95)$p.value
  p2f = formatC(p2, digits = 3, format = 'f')
  # p1 = p2/2
  # p1f = formatC(p1, digits = 3, format = 'f')
  
  corners = par("usr")
  
  mtext(paste0('KS-test: $p=',pf,'$',funcstar(p),
'\nt-test: $p=',p2f,'$',funcstar(p2)
               ),side=3, line = 0, cex = 1)
}

textlabel <- function (ser){
paste0('$n =', format(length(ser),big.mark=","),'$\r
$\\mu =',round(mean(ser),3) %>% format(.,digits=3,nsmall=3,scientific =F, big.mark=','),'$\r
$\\sigma =',round(sd(ser),3)%>% format(.,digits=3,nsmall=3,scientific =F, big.mark=','),'$\r
$\\gamma =',round(skewness(ser),3)%>% format(.,digits=3,nsmall=3,scientific =F, big.mark=','),'$\r
$\\kappa =',round(kurtosis(ser),3)%>% format(.,digits=3,nsmall=3,scientific =F, big.mark=','),'$')
}

# average trading intensity given age and calendar date

pickdates = c('2012-12-31','2014-12-31', '2016-12-31') %>% as.Date()

```

```{r desc, eval=F}
load('regtable.rda')
load('cl_transferin.rda')
popweight = regtable[, list(wt = 1/(.N)), by = firstobs][order(firstobs)]
regtable = regtable[!(
  client %in% unique(c(cl_transferin
                       # , cl_transferout
                       ))
  ), list(
    firstobs = firstobs,
    closing_date = closing_date,
    lastobs = lastobs
  )]


data = merge(regtable[, list(close = .N), by = format(closing_date, '%Y-12-31')%>% as.Date],
      regtable[, list(open = .N), by = format(firstobs, '%Y-12-31') %>% as.Date]
      )[, ':='(opencum = cumsum(open), closecum = cumsum(close))
        ][, eop := opencum - closecum][, ymax := eop + close]

names(data)[1] = 'date'

df = data[, c('date', 'open', 'close', 'eop', 'ymax')] %>% 
  melt(id.vars = c("date", "eop", "ymax")) %>% 
  mutate(ymin = ymax - value) %>% 
  rename(group = variable)

step = 90
# Define xmin and xmax of segments
df <- df %>% 
  mutate(xmin = case_when(
    group == "open" ~ date - step,
    TRUE ~ date 
  )) %>% 
  mutate(xmax = case_when(
    group == "open" ~ date,
    TRUE ~ date + step
  ))


# Create waterfall chart
df %>% 
  arrange(date) %>% 
  ggplot() +
  geom_rect(aes(xmin = xmin,
                xmax = xmax,
                ymin = ymin,
                ymax = ymax,
                fill = group)) -> p1
p1

# Create data for line chart
df2 <- df %>% select(date, eop) %>% distinct()

# Optimize colors, themes & add lines
p2 <- p1  + 
  geom_line(aes(date, eop), col = "dodgerblue4", size = 0.8) +
  geom_point(aes(date, eop), col = "dodgerblue4", size = 1) +
  geom_text(aes(date, eop, label = eop), vjust = 1.2, 
            hjust = -0.1, size = 3) +
  scale_fill_manual(values = c("grey60", "coral2")) +
  theme_minimal() +
  theme(
    axis.line = element_line(color = "gray40", size = 0.5),
    legend.position = "top") +
  scale_x_date(breaks = data$date,
               date_labels = "%Y") +
  theme(panel.grid.minor.x = element_blank(),
        legend.title = element_blank()) +
  xlab("Date") + 
  ylab("Number of clients")
p2


# 
# p3 <- df %>% 
#   mutate(value = case_when(
#     group == "close" ~ -1 * value,
#     TRUE ~ value
#   )) %>% 
#   ggplot(aes(date, value)) +
#   geom_bar(aes(fill = group), stat = "identity") +
#   scale_fill_manual(values = c("grey60", "coral2")) +
#   theme_minimal() +
#   theme(
#     legend.position = "none",
#     axis.title.x = element_blank(),
#     axis.title.y = element_blank(),
#     axis.ticks.y = element_blank(),
#     axis.text.y = element_blank(),
#     panel.grid.minor = element_blank(),
#     panel.grid.major = element_blank(),
#     axis.text.x = element_text(angle = 90)
#   ) +
#   scale_x_date(breaks = data$date,
#                date_labels = "%Y") 
# p3
# 
# 
# grid.newpage()
# 
# # Define position of the main chart
# position_1 <- viewport(width = 1, height = 1, x = 0.5, y = 0.5)  # the larger map
# 
# # Position of the secondary chart
# position_2 <- viewport(width = 0.35, height = 0.25, x = 0.25, y = 0.75)  
# 
# print(p2, vp = position_1)
# print(p3, vp = position_2)
```

```{r dailyperf, eval=F}
load('regtable.rda')
gc()
if(!exists('clientdaily')){load('clientdaily2.rda')}


clientdaily = merge(clientdaily, regtable[,c('client', 'closing_date','firstobs', 'lastobs')], by = 'client', all.x = T)

gc()
clientdaily[,':='(daily_perf_excess = daily_perf - smidailyret,
                   age = account_date - firstobs)]

clientdaily[, nclient := .N, by=client]

clientdaily[nclient > 365, rreturn365 := rollsum(
                daily_perf, 365, na.rm = T, align = 'right', fill = NA
                ), by = client]

clientdaily365 = clientdaily
save(clientdaily365, file = 'clientdaily365.rda')

for (nroll in nrolls){ # size of rolling window
  gc()
  # rolling return
  clientdaily[nclient > nroll, paste0('raprofit', nroll) := rollsum(
                daily_perf_excess, nroll, na.rm = T, align = 'right', fill = NA
                ), by = client]
    clientdaily[nclient > nroll, paste0('raprofitfw', nroll) := rollsum(
                daily_perf_excess, nroll, na.rm = T, align = 'left', fill = NA
                ), by = client]
}

gc()
clientdaily = clientdaily[order(account_date)]
gc()

clientdaily[, cumret := cumsum(ifelse(is.na(daily_perf_excess), 0, daily_perf_excess)), by = client]
gc()

clientdaily[, avgcumret := cumret / as.numeric(age), by = client]

gc()
clientdaily[is.finite(daily_perf_excess), meancumret := cummean(daily_perf_excess), by = client]

clienttemp = clientdaily[, sum(is.finite(meancumret)), by = client][V1>1]$client
gc()
clientdaily[client %in% clienttemp, meanappret := approx(account_date, meancumret, xout = account_date)$y, by = client]
gc()

save(clientdaily, file = 'clientdaily.rda')


# meanexret = clientdaily[, list(mexret = mean(daily_perf_excess, na.rm=T)), by = account_date][order(account_date)]
# 
# meanexret = meanexret[, list(
#   account_date,
#   mexret,
#   mexret183 = rollsum(mexret, nrolls[1], na.rm = T, align = 'right', fill = NA),
#   mexret365 = rollsum(mexret, nrolls[2], na.rm = T, align = 'right', fill = NA),
#   mexret548 = rollsum(mexret, nrolls[3], na.rm = T, align = 'right', fill = NA)
#   )]
# 
# 
# # the problem w. SQ is that history is too short, and calendar effects intertwine with individual effect
# popweight = regtable[, list(wt = 1/(.N)), by = firstobs]
# temp = merge(popweight, clientdaily[, c('account_date', 'daily_perf_excess', 'firstobs')
#                                     ], by = 'firstobs')
# 
# meanexretwt = temp[, list(mexret = weighted.mean(daily_perf_excess, na.rm=T, weigh = wt)), by = account_date][order(account_date)]
# 
# meanexretwt = meanexretwt[, list(
#   account_date,
#   mexret,
#   mexret183 = rollsum(mexret, nrolls[1], na.rm = T, align = 'right', fill = NA),
#   mexret365 = rollsum(mexret, nrolls[2], na.rm = T, align = 'right', fill = NA),
#   mexret548 = rollsum(mexret, nrolls[3], na.rm = T, align = 'right', fill = NA)
#   )]
# 
# 
# meanexret[, plot(account_date, mexret365, type = 'l')]
# meanexretwt[, plot(account_date, mexret548, type = 'l')]


save(meanexret, file = 'meanexret.rda')
```  

```{r DailyExit, eval=T}
load('regtable.rda')
load('cl_transferin.rda')

regtable = regtable[!(
  client %in% unique(c(cl_transferin
                       # , cl_transferout
                       ))
  ), list(
    firstobs = firstobs,
    closing_date = closing_date,
    lastobs = lastobs
  )]

if(!(exists('clientdaily2')|exists('clientdaily'))){
  load('clientdaily.rda')}

par(mgp=c(1.5,0.5,0), xpd = F)
# use last year return
for(i in 1:2){
  temp = clientdaily[firstobs > c('2001-01-01', '2009-01-01')[i] & account_date < '2017-12-31' & age > 365,
                   list(account_date = account_date,
                        closing_date = closing_date,
                   ret =  get(c('raprofit365', 'meanappret')[i]),
                   age = age)]
temp[, retpr := ecdf(ret)(ret), by = account_date]
temp[, retgroup := cut(retpr, seq(0,1,1/3), labels = F)]

temp[, agepr := ecdf(age)(age), by = c('account_date', 'retgroup')]
temp[, agegroup := cut(agepr, seq(0,1,1/3), labels = F)]

temp[, ':='(retpr = NULL, agepr = NULL)]

for(j in 1:3){
  xx = temp[retgroup == j & account_date > '2011-01-01']
  tempplot = xx[, list(ttln =.N, exitn = sum(account_date > closing_date - 365.2425, na.rm = T)), by = c('account_date', 'agegroup')]
  tempplot[agegroup == 3, plot(account_date, exitn/ttln, type = 'l', ylim = c(0, 0.08),
                               xlab = 'Calendar date', ylab = 'Exit rate over the next year')]
  tempplot[agegroup == 2, lines(account_date, exitn/ttln, col = 'blue')]
  tempplot[agegroup == 1, lines(account_date, exitn/ttln, col = 'red')]
  legend('topleft', lty = 1, legend = c('Highest', 'Middle', 'Lowest') %>% paste(., 'tertile'), 
       title = 'Trading age', col = c('black', 'blue', 'red'), bty = 'n')
  
  assign(paste0('ExitTS', i, j), recordPlot()) 

}
}

save(ExitTS11, ExitTS12, ExitTS13, ExitTS21, ExitTS22, ExitTS23, file = 'ExitTS.rda')


temp = clientdaily[firstobs > c('2001-01-01', '2009-01-01')[i] & account_date < '2017-12-31' & age > 365,
                   list(account_date = account_date,
                        closing_date = closing_date,
                   ret =  raprofit365,
                   age = age)]
temp[, retpr := ecdf(ret)(ret), by = account_date]
temp[, retgroup := cut(retpr, seq(0,1,1/3), labels = F)]

temp[, agepr := ecdf(age)(age), by = c('account_date', 'retgroup')]
temp[, agegroup := cut(agepr, seq(0,1,1/6), labels = F)]

temp[, ':='(retpr = NULL, agepr = NULL)]

for(j in 1:3){
  xx = temp[retgroup == j & account_date > '2011-01-01']
  tempplot = xx[, list(ttln =.N, exitn = sum(account_date > closing_date - 365.2425, na.rm = T)), by = c('account_date', 'agegroup')]
  tempplot[agegroup == 2, plot(account_date, exitn/ttln, type = 'l', ylim = c(0, 0.08),
                               xlab = 'Calendar date', ylab = 'Exit rate over the next year')]
  # tempplot[agegroup == 2, lines(account_date, exitn/ttln, col = 'blue')]
  tempplot[agegroup == 1, lines(account_date, exitn/ttln, col = 'red')]
  legend('topleft', lty = 1, legend = c('Second', 'Lowest') %>% paste(., 'sextile'), 
       title = 'Trading age', col = c('black', 'red'), bty = 'n')
  
  assign(paste0('ExitTSthird', j), recordPlot()) 

}


save(ExitTSthird1, ExitTSthird2, ExitTSthird3, file = 'ExitTSthird.rda')








xx = merge(regtable[, .N, by = closing_date][order(closing_date)],masstblfull ,
           by.x = 'closing_date', by.y = 'date_trans', all.y = T)


clientdaily[, plot(account_date, raprofit365, type = 'l', axes = F, ann=F
                 , xlim=c('2009-06-01', '2017-07-01') %>% as.Date, col = 'red')]
axis(4, col = 'red')
par(new=T)
xx[, plot(closing_date,
          rollsum(N, 365, na.rm = T, na.pad = T, align = 'left')/rollmean(ttln, 365, na.rm = T, na.pad = T, align = 'left'), col = 'black', type = 'l', ylab = '', ann=F, xlim=c('2009-06-01', '2017-07-01') %>% as.Date)]

```  

```{r ReturnbyAgeExit, eval=T}
load('regtable.rda')
load('cl_transferin.rda')
popweight = regtable[, list(wt = 1/(.N)), by = firstobs][order(firstobs)]
regtable = regtable[!(
  client %in% unique(c(cl_transferin
                       # , cl_transferout
                       ))
  ), list(
    firstobs = firstobs,
    closing_date = closing_date,
    lastobs = lastobs
  )]

# if(!(exists('clientdaily2')|exists('clientdaily'))){
#   load('clientdaily.rda')}

# use last year retur
  temp = xx[account_date < '2017-12-31' & age > 365,
                   list(account_date = account_date,
                        closing_date = closing_date,
                   ret =  rreturn365,
                   firstobs = firstobs.x,
                   age = age)]  # %>% merge(popweight) by age-time, no need for weight

temp[, agepr := ecdf(age)(age), by = c('account_date')]
temp[, agegroup := cut(agepr, seq(0,1,1/3), labels = F)]

temp[, ':='(agepr = NULL)]

par(mgp=c(1.5,0.5,0), xpd = F)

for(j in 1:3){
  xx = temp[agegroup == j & account_date > '2011-01-01'][order(account_date)]
  xx[, exinextyr := ifelse(is.na(closing_date), F, account_date > closing_date - 365.2425)]
  tempplot = xx[, list(mret = mean(ret, na.rm = T),
                       conf1 = t.test(ret)$conf.int[1],
                       conf2 = t.test(ret)$conf.int[2]), by = c('account_date', 'exinextyr')]
  tempplot[exinextyr == F, plot(account_date, mret, type = 'l', 
                                ylim = c(-0.4, 0.12),
                               xlab = 'Account date', ylab = 'Average one-year relative log return')]
  tempplot[exinextyr == F, polygon(x=c(account_date,rev(account_date)), y = c(conf1, rev(conf2)), col = adjustcolor('black', 0.2), border = NA)]
  tempplot[exinextyr == T, lines(account_date, mret, col = 'red')]
  tempplot[exinextyr == T, polygon(x=c(account_date,rev(account_date)), y = c(conf1, rev(conf2)), col = adjustcolor('red', 0.2), border = NA)]
  xx[exinextyr == F, abline(h=mean(ret), lty = 2, col = 'black')]
  xx[exinextyr == T, abline(h=mean(ret), lty = 2, col = 'red')]
  # abline(h=0, col = 'gray')
  legend('bottom', lty = c(1,1,2,2), 
         legend = c('Reamin throughout next year', 'Exit during next year', 'Overall mean of remain', 'Overall mean of exit'), 
         col = c('black', 'red'), bty = 'n')
  
  assign(paste0('ReturnbyAgeExit', j), recordPlot()) 

}


save(ReturnbyAgeExit1, ReturnbyAgeExit2, ReturnbyAgeExit3, file = 'ReturnbyAgeExit.rda')

```  

```{r SMI, eval=T}
load('regtable.rda')
load('cl_transferin.rda')

regtable = regtable[!(
  client %in% unique(c(cl_transferin
                       # , cl_transferout
                       ))
  ), list(
    firstobs = firstobs,
    closing_date = closing_date,
    lastobs = lastobs
  )]

load('clientdaily365.rda')
load('clientdaily.rda')

SMI = clientdaily[, c('account_date', 'smidailyret')] %>% unique

SMI = merge(data.table(account_date = seq.Date(as.Date('2009-01-01'), as.Date('2018-12-28'), 1)), SMI, by = 'account_date', all = T)[order(account_date)]

SMI[, smi365 := rollsum(smidailyret, 365, align = 'right', na.rm = T, fill = NA)]

manra365rel = clientdaily[, mean(raprofit365, na.rm = T), by = account_date]
manraday = clientdaily365[, mean(daily_perf, na.rm = T), by = account_date][order(account_date)]
manraday[, raday365 := rollsum(V1, 365, align = 'right', na.rm = T, fill = NA)]

manra365 = clientdaily365[, mean(rreturn365, na.rm = T), by = account_date][order(account_date)]


par(mgp=c(1.5,0.5,0), xpd = F)

SMI[3000:9000,plot(account_date, smi365, type = 'l', ylim = c(-0.36,0.3), xaxs = 'i',
    xlab = 'Calendar date', ylab = 'One-year log return', lty = 2)]
manra365rel[,lines(account_date, V1, col = 'blue')]
manra365[,lines(account_date, V1, col = 'red')]
abline(h = 0, col = 'gray')
legend('bottom', lty = 1, legend = c('SMI', 'Average client'), col = c('black','red'), bty = 'n')
logreturnTS = recordPlot()

save(logreturnTS, file = 'logreturnTS.rda')


# manraday[,lines(account_date, raday365, col = 'red')]
# clientdaily[, t.test(raprofit183,raprofitfw183)]
# clientdaily[, t.test(raprofit365,raprofitfw365)]
# clientdaily[, t.test(raprofit548,raprofitfw548)]
```

```{r coxreori, eval=T}
# load('clientdaily365.rda')
load('coxphbasefit.rda')
load('coxphbasefitextfit.rda')

coxbase = data.table(time = coxphbasefit$time, cumhaz = coxphbasefit$cumhaz)[coxphbasefit$n.risk > 200]
coxext = data.table(time = coxphbasefitextfit$time, cumhaz = coxphbasefitextfit$cumhaz)[coxphbasefitextfit$n.risk > 200]

coxbase[, plot(time, cumhaz, type = 'l')]
coxext[, plot(time, cumhaz, type = 'l')]

tbl = coxbase[seq(1, .N, length.out = 30),]
tbl[, hazrate := c(0, diff(cumhaz)/diff(time))]
tbl[, plot(time,  hazrate, type = 'l')]


tbl = coxext[seq(1, .N, length.out = 30),]
tbl[, hazrate := c(0, diff(cumhaz)/diff(time))]
tbl[, plot(time,  hazrate, type = 'l')]

gc()

load('regtable.rda')
load('cl_transferin.rda')
regtable = regtable[!(
  client %in% unique(c(cl_transferin
                       # , cl_transferout
                       ))
  )]
#

survtemp = survfit(Surv(lifetime,uncensored)~1, data = regtable)

tbl = summary(survtemp)[c(
  "time", "n.risk", "n.event", "surv", "std.err", "lower", "upper"
  )] %>% as.data.table
tbl = tbl[seq(1, .N - 400, length.out = 40),]
tbl[, ':='(survm1 = c(1, surv[-length(surv)]), timem1 = c(0.25, time[-length(surv)]))]
tbl[, mort := 1- (surv/survm1)^(1/(time-timem1))]
tbl[, plot(time,  mort, type = 'l')]
# # load('clientdaily.rda') #big and useless, not merged with regtable

```

```{r coxre, eval=T}
load('data/tsregressreg.rda')

# xx = merge(regtable, xx)
# # save(xx, file = 'tsregressreg.rda')
# 
xx[, ':='(firstobs.y = NULL)]
xx[is.finite(rreturn365), ':='(
    retpr = ecdf(rreturn365)(rreturn365)), by = account_date]
xx[, ':='(retprind = ecdf(retpr)(retpr),
          retind = ecdf(rreturn365)(rreturn365)), by = client]

## important: People exit both when return is high and when return is low… but model does not predict that so whatever..
# xx[account_date == closing_date & age > 365.2425 * 3, retprind %>% density(cut = 0) %>% plot]
# xx[account_date == closing_date & age < 365.2425 * 3, retprind %>% density(cut = 0) %>% lines(col='red')]


temp = xx[account_date < '2017-12-31' & age > 365.2425 * 3,
                   list(account_date = account_date,
                        closing_date = closing_date,
                   retpr =  retpr,
                   age = age)]
# temp[, retpr := ecdf(ret)(ret), by = account_date]
temp[, retgroup := cut(retpr, seq(0,1,1/3), labels = F)]
# 
temp[, agepr := ecdf(age)(age), by = c('account_date', 'retgroup')]
temp[, agegroup := cut(agepr, seq(0,1,1/3), labels = F)]
# 
# temp[, ':='(retpr = NULL, agepr = NULL)]

for(j in 1:3){
  temp1 = temp[retgroup == j & account_date > '2011-01-01'][order(account_date)]
  tempplot = temp1[, list(ttln =.N, exitn = sum(account_date > closing_date - 365.2425, na.rm = T)), by = c('account_date', 'agegroup')]
  tempplot[agegroup == 3, plot(account_date, exitn/ttln, type = 'l', ylim = c(0, 0.08),
                               xlab = 'Calendar date', ylab = 'Exit rate over the next year')]
  tempplot[agegroup == 2, lines(account_date, exitn/ttln, col = 'blue')]
  tempplot[agegroup == 1, lines(account_date, exitn/ttln, col = 'red')]
  legend('topleft', lty = 1, legend = c('Second', 'Lowest') %>% paste(., 'sextile'), 
       title = 'Trading age', col = c('black', 'red'), bty = 'n')
  
  assign(paste0('ExitTg3', j), recordPlot()) 

}


sumtbl = function(ans){
  temp = ans$coefficients[, c('Estimate', 'Pr(>|t|)')] %>% as.data.table(keep.rownames=T)
  names(temp)[3] = 'pv'
  temp[, ':='(p = paste0("'(", round(pv,3) %>% format(nsmall = 3), ')'),
              str = funcstar(pv))]
  nr = nrow(temp)
  tbl = data.table(rn = rep('', 2*nr+2))
  tbl[seq(1,nr*2,2), 'rn'] = temp$rn
  tbl[seq(2,nr*2,2), 'rn'] = temp$rn %>% paste0('p')
  tbl[seq(2,nr*2,2), 'beta'] = temp$p
  tbl[seq(1,nr*2,2), 'beta'] = temp$Estimate
  tbl$str = ''
  tbl[seq(1,nr*2,2), 'str'] = temp$str
  tbl[nr*2+1, 1] = 'R2'
  tbl[nr*2+1, 2] = ans$r.squared
  tbl[nr*2+2, 1] = 'n'
  tbl[nr*2+2, 2] = ans$residuals %>% length
  return(tbl)
  }

tbl = data.table(rn = '')

retproxy = 'retpr'

n=0
xx[account_date == closing_date, lm(get(retproxy) ~ age)] %>% summary() -> ans
tbl %<>% merge(sumtbl(ans), by = 'rn', all = T, sort = F, suffixes = n:(n+1))
n = n+2

xx[account_date == closing_date, lm(get(retproxy) ~ age + gender)] %>% summary() -> ans
tbl %<>% merge(sumtbl(ans), by = 'rn', all = T, sort = F, suffixes = n:(n+1))
n = n+2

xx[account_date == closing_date, lm(get(retproxy) ~ age + enterage)] %>% summary() -> ans
tbl %<>% merge(sumtbl(ans), by = 'rn', all = T, sort = F, suffixes = n:(n+1))
n = n+2

xx[account_date == closing_date, lm(get(retproxy) ~ age + TradesOptions)] %>% summary() -> ans
tbl %<>% merge(sumtbl(ans), by = 'rn', all = T, sort = F, suffixes = n:(n+1))
n = n+2

xx[account_date == closing_date, lm(get(retproxy) ~ age + gender + enterage + TradesOptions)] %>% summary() -> ans
tbl %<>% merge(sumtbl(ans), by = 'rn', all = T, sort = F, suffixes = n:(n+1))
n = n+2

write.csv(tbl, file='tbl.csv')


xx[account_date == closing_date & age < 365.2425 * 3, lm(retprind ~ age)] %>% summary() -> ans
tbl %<>% merge(sumtbl(ans), by = 'rn', all = T, sort = F, suffixes = n:(n+1))
n = n+2

xx[account_date == closing_date & age < 365.2425 * 3, lm(retprind ~ age + gender + enterage + TradesOptions)] %>% summary() -> ans
tbl %<>% merge(sumtbl(ans), by = 'rn', all = T, sort = F, suffixes = n:(n+1))
n = n+2

xx[account_date == closing_date & age >= 365.2425 * 3, lm(retprind ~ age)] %>% summary() -> ans
tbl %<>% merge(sumtbl(ans), by = 'rn', all = T, sort = F, suffixes = n:(n+1))
n = n+2

xx[account_date == closing_date & age >= 365.2425 * 3, lm(retprind ~ age + gender + enterage + TradesOptions)] %>% summary() -> ans
tbl %<>% merge(sumtbl(ans), by = 'rn', all = T, sort = F, suffixes = n:(n+1))

write.csv(tbl, file='tbl.csv')


xx[account_date == closing_date, lm(retind ~ age)] -> ans
ans$residuals %>% length()
ans %>% summary()
xx[account_date == closing_date, lm(retind ~ age + gender + enterage + TradesOptions)] -> ans
ans$residuals %>% length()
ans %>% summary()

xx[account_date == closing_date & age < 365.2425 * 3, lm(retind ~ age)] -> ans
ans$residuals %>% length()
ans %>% summary()
xx[account_date == closing_date & age < 365.2425 * 3, lm(retind ~ age + gender + enterage + TradesOptions)] -> ans
ans$residuals %>% length()
ans %>% summary()

xx[account_date == closing_date & age >= 365.2425 * 3, lm(retind ~ age)] -> ans
ans$residuals %>% length()
ans %>% summary()
xx[account_date == closing_date & age >= 365.2425 * 3, lm(retind ~ age + gender + enterage + TradesOptions)] -> ans
ans$residuals %>% length()
ans %>% summary()



xx[account_date == closing_date, lm(retpr ~ age)] -> ans
ans$residuals %>% length()
ans %>% summary()
xx[account_date == closing_date, lm(retpr ~ age + gender + enterage + TradesOptions)] -> ans
ans$residuals %>% length()
ans %>% summary()

xx[account_date == closing_date & age < 365.2425 * 3, lm(retpr ~ age)] -> ans
ans$residuals %>% length()
ans %>% summary()
xx[account_date == closing_date & age < 365.2425 * 3, lm(retpr ~ age + gender + enterage + TradesOptions)] -> ans
ans$residuals %>% length()
ans %>% summary()

xx[account_date == closing_date & age >= 365.2425 * 3, lm(retpr ~ age)] -> ans
ans$residuals %>% length()
ans %>% summary()
xx[account_date == closing_date & age >= 365.2425 * 3, lm(retpr ~ age + gender + enterage + TradesOptions)] -> ans
ans$residuals %>% length()
ans %>% summary()


xx[account_date == closing_date, lm(rreturn365 ~ age)] -> ans
ans$residuals %>% length()
ans %>% summary()
xx[account_date == closing_date, lm(rreturn365 ~ age + gender + enterage + TradesOptions)] -> ans
ans$residuals %>% length()
ans %>% summary()

xx[account_date == closing_date & age < 365.2425 * 3, lm(rreturn365 ~ age)] -> ans
ans$residuals %>% length()
ans %>% summary()
xx[account_date == closing_date & age < 365.2425 * 3, lm(rreturn365 ~ age + gender + enterage + TradesOptions)] -> ans
ans$residuals %>% length()
ans %>% summary()

xx[account_date == closing_date & age >= 365.2425 * 3, lm(rreturn365 ~ age)] -> ans
ans$residuals %>% length()
ans %>% summary()
xx[account_date == closing_date & age >= 365.2425 * 3, lm(rreturn365 ~ age + gender + enterage + TradesOptions)] -> ans
ans$residuals %>% length()
ans %>% summary()

# yy = xx[, c('client','gender', 'rreturn365', 'TradesOptions', 'account_date' , 'closing_date', 'age', 'enterage')]
# rm(xx)
# gc()
# yy[is.finite(rreturn365), ':='(
#     retpr = ecdf(rreturn365)(rreturn365)), by = account_date]
# 
# yy[, ':='(ageplus1 = age + 1)][, ':='(
#   event = ifelse(is.finite(closing_date), closing_date == account_date, F))]
# 
# 
# coxphbase = coxph(Surv(time = age, time2 = ageplus1, event = event) ~  retpr + cluster(client), data = yy)
# # baseline never changes irrespective of cluster!!!?
# summary(coxphbase)
# coxphbasefit = survfit(coxphbase)
# 
# coxphbaseext = coxph(Surv(time = age, time2 = ageplus1, event = event) ~  
#         retpr + gender + enterage + TradesOptions +  cluster(client), data = yy)
# summary(coxphbaseext)
# coxphbasefitextfit = survfit(coxphbaseext)
# 
# save(coxphbase, coxphbasefit, coxphbaseext, coxphbasefitextfit, file = 'coxph.Rda')
# 
# # with(data = yyy[1000:4000,], plot(time,hazard))
# temp = yyy[seq(1,5700,length.out = 40),] %>% data.table()
# plot(temp$time[-1], diff(temp$hazard), type = 'l')
# 
# 
# 
# aaa5 = coxph(Surv(time = age, time2 = ageplus1, event = event) ~  retpr + strata(I(age < 3*365.2425)), data = yy)
# # baseline never changes no matter what model you use! (is baseline the non-parametric Kaplan-Maier model)?
# yyy5= basehaz(aaa)
# with(data = yyy5[1000:4000,], plot(time,hazard))
# 
# gc()
# aaa6 = coxph(Surv(time = age, time2 = ageplus1, event = event) ~  retpr + strata(I(retpr < 1/3)), data = yy)
# # baseline never changes no matter what model you use! (is baseline the non-parametric Kaplan-Maier model)?
# yyy6= basehaz(aaa)
# with(data = yyy6[1000:4000,], plot(time,hazard))
# 
# aaa7 = coxph(Surv(time = age, time2 = ageplus1, event = event) ~  retpr + strata(I(retpr >= 1/3)), data = yy)
# # baseline never changes no matter what model you use! (is baseline the non-parametric Kaplan-Maier model)?
# yyy7= basehaz(aaa)
# with(data = yyy7[1000:4000,], plot(time,hazard))
# 
# 
# aaa2 = coxph(Surv(time = age, time2 = ageplus1, event = event) ~  retpr + cluster(client), data = yy)
# yyy2= basehaz(aaa2)
# with(data = yyy2[1000:4000,], plot(time,hazard))
# 
# aaa3 = coxph(Surv(time = age, time2 = ageplus1, event = event) ~ 1, data = yy)
# yyy3= basehaz(aaa3)
# with(data = yyy3[1000:4000,], plot(time,hazard))
# 
# 
# 
# 
# # try age strata later agter daniel
# coxph(Surv(time = age, time2 = ageplus1, event = event) ~  
#         retpr + cluster(client), data = yy)
# 
# coxph(Surv(time = age, time2 = ageplus1, event = event) ~  
#         retpr + cluster(client), data = yy[age<3*365.2425], 
#       tt =  function(x, t, ...) x * t)
# 
# coxph(Surv(time = age, time2 = ageplus1, event = event) ~  
#         retpr + tt(retpr) + cluster(client), data = yy[age<3*365.2425], 
#       tt =  function(x, t, ...) x * t)
#   
# coxph(Surv(time = age, time2 = ageplus1, event = event) ~  
#         retpr + tt(retpr) + cluster(client), data = yy[age>=3*365.2425], 
#       tt =  function(x, t, ...) x * t)
# 
# 
# coxph(Surv(time = age, time2 = ageplus1, event = event) ~  
#         retpr + tt(retpr), data = yy[age>=3*365.2425], 
#       tt =  function(x, t, ...) x * t)
# 
# coxph(Surv(time = age, time2 = ageplus1, event = event) ~  
#         retpr + cluster(client), data = yy[age>=3*365.2425], 
#       tt =  function(x, t, ...) x * t)
# 
# 
# # coxph(Surv(time = age, time2 = ageplus1, event = event) ~
# #         rreturn365 + gender + enterage + TradesOptions + cluster(client), data = yy)
# 



```

```{r regress, eval=T}
gc()

xx[account_date < '2018-01-01', ':='(
  ExitNxtYr = ifelse(is.finite(closing_date), (closing_date - account_date) < 365.2425, F))]

library(glmmML)

gc()

aa =  glmmboot(ExitNxtYr ~ age + rreturn365 + gender + enterage + TradesOptions, family=binomial(link="logit"), data=xx[age < 365.2425 *3], cluster=account_date, na.action=na.omit)
aa$n
aa$logLik
summary(aa)

gc()
aa =  glmmboot(ExitNxtYr ~ age + rreturn365 + gender + enterage + TradesOptions, family=binomial(link="logit"), data=xx[age >= 365.2425 *3], cluster=account_date, na.action=na.omit)
aa$n
aa$logLik
summary(aa)

gc()
aa =  glmmboot(ExitNxtYr ~ age + rreturn365 + gender + enterage + TradesOptions, family=binomial(link="logit"), data=xx, cluster=account_date, na.action=na.omit)
aa$n
aa$logLik
summary(aa)



aa = pglm(ExitNxtYr ~ age + rreturn365, data = xx[age < 365.2425 *3], na.action=na.omit, family = binomial(link = 'logit'), index = c('client', 'account_date'), effect = 'time', model=("pooling"))
aa %>% summary

gc()
aa = pglm(ExitNxtYr ~ age + rreturn365, data = xx[age >= 365.2425 *3,], na.action=na.omit, family = binomial('probit'), index = c('client', 'account_date'), effect = 'time', model = "pooling",  method = "bfgs")
aa %>% summary


gc()
time = Sys.time()
xxplmg = plm(rreturn365 ~ age + enterage,
data = xx, index = c('client', 'account_date'), effect = 'twoways')
Sys.time() - time
summary(xxplmg)

rm(xxplmg)
gc()
time = Sys.time()
xxplmg = plm(rreturn365 ~ age + gender + enterage,
data = xx, index = c('client', 'account_date'), effect = 'twoways')
Sys.time() - time
summary(xxplmg)


rm(xxplmg)
gc()
time = Sys.time()
xxplmg = plm(rreturn365 ~ age + TradesOptions,
data = xx, index = c('client', 'account_date'), effect = 'twoways')
Sys.time() - time
summary(xxplmg)

rm(xxplmg)
gc()
time = Sys.time()
xxplmg = plm(rreturn365 ~ age + TradesOptions + nsec + ntrade,
data = xx, index = c('client', 'account_date'), effect = 'twoways')
Sys.time() - time
summary(xxplmg)


rm(xxplmg)
gc()
time = Sys.time()
xxplmg = plm(rreturn365 ~ age + gender + enterage + TradesOptions + nsec + ntrade,
data = xx, index = c('client', 'account_date'), effect = 'twoways')
Sys.time() - time
summary(xxplmg)

# xx = merge(regtable[,c('client', 'firstobs')], clientdaily365[is.finite(rreturn365) & account_date >= '2010-01-01'], by = 'client')
# xx[, age := account_date - firstobs]
# gc()
# save(xx, file = 'tsregressreg.rda')
# 
# 
# 
# xxplmind = plm(rreturn365 ~ age, data = xx, index = c('account_date','client'))
# 
# 
# xxlm = lm(rreturn365 ~ age, data = xx)
# summary(xxlm)
# 
# xxplmind.sum = summary(xxplmind)
# 
# save(xxplmind.sum, file ='xxplmind.sum.rda')
# load('xxplmind.sum.rda')
# 
# 
# 
# xx = xx[,c('client', 'account_date','rreturn365','age')]
# gc()

# # This is identical to xxplmind
# xxplmindtime = plm(rreturn365 ~ age, data = xx, index = c('client', 'account_date'), effect = 'time')
# 
# gc()
# xxplmindtime.sum = summary(xxplmindtime)
# gc()
# 
# save(xxplmindtime.sum, file ='xxplmindtime.sum.rda')

## does not work -- funky coefficient
# xxplmindtw = plm(rreturn365 ~ age, data = xx[client < 210000 & account_date > 2018-06-01], index = c('client', 'account_date'), effect = 'twoways')


load('xxplmindtime.sum.rda')
```

```{r DailyReturn, eval=T}
# remember to always use after 2010 data for age-return relationship -- because we do not have data before that

popweight = regtable[, list(wt = 1/(.N)), by = firstobs][order(firstobs)]
pops = merge(regtable, popweight)


# 365-day return
# backward -- based on your current age percentile, what was your historical 365-day return
temp2 = clientdaily[firstobs > '2010-01-01' & account_date < '2018-12-31' & age > 365,
                   list(account_date = account_date,
                   ret =  raprofit365,
                   age = age)]
temp2[, agepr := ecdf(age)(age), by = account_date]

temp2[, agegroup := cut(agepr, seq(0,1,1/3), labels = F)]

tempplot2 = temp2[, list(mret = mean(ret, na.rm = T),
                        conf1 = t.test(ret)$conf.int[1],
                        conf2 = t.test(ret)$conf.int[2]), 
                by = c('account_date', 'agegroup')][order(account_date)]


# forward -- based on your current age percentile, what will be your future 365-day return
temp = clientdaily[firstobs > '2009-01-01' & account_date < '2017-12-31' & age > 365,
                   list(account_date = account_date,
                   ret =  raprofitfw365,
                   age = age)]
temp[, agepr := ecdf(age)(age), by = account_date]

temp[, agegroup := cut(agepr, seq(0,1,1/3), labels = F)]

tempplot = temp[, list(mret = mean(ret, na.rm = T),
                        conf1 = t.test(ret)$conf.int[1],
                        conf2 = t.test(ret)$conf.int[2]), 
                by = c('account_date', 'agegroup')][order(account_date)]

xx = merge(tempplot,tempplot2, by = c('account_date','agegroup'),suffixes = c("bw","fw"))
xx[agegroup == 1, t.test(mretfw,mretbw, paired = T)]
xx[agegroup == 2, t.test(mretfw,mretbw, paired = T)]
xx[agegroup == 3, t.test(mretfw,mretbw, paired = T)]


t.test(tempplot[agegroup == 1, mret],tempplot2[agegroup == 1, mret][-1], paired = T)
t.test(tempplot[agegroup == 2, mret],tempplot2[agegroup == 2, mret][-1], paired = T)
t.test(tempplot[agegroup == 3, mret],tempplot2[agegroup == 3, mret][-1], paired = T)


par(mgp=c(1.5,0.5,0), xpd = F)

for(i in 1:2){
  temp = list(tempplot, tempplot2)[[i]]
 yrange = range(temp$mret, na.rm = T)
temp[agegroup == 3, plot(account_date, mret, type = 'l', ylim = yrange, 
                             xlim =c('2011-07-01','2017-06-30') %>% as.Date, main = '', xlab = 'Account date', ylab = paste('Average log relative return \nduring one year', c('forward','backward')[i]))]
temp[agegroup == 3, lines(account_date, conf1, lty = 2)]
temp[agegroup == 3, lines(account_date, conf2, lty = 2)]
temp[agegroup == 2, lines(account_date, mret, col = 'blue')]
temp[agegroup == 2, lines(account_date, conf1, col = 'blue', lty = 2)]
temp[agegroup == 2, lines(account_date, conf2, col = 'blue', lty = 2)]
temp[agegroup == 1, lines(account_date, mret, col = 'red')]
temp[agegroup == 1, lines(account_date, conf1, col = 'red', lty = 2)]
temp[agegroup == 1, lines(account_date, conf2, col = 'red', lty = 2)]
legend('topleft', lty = 1, legend = c('Highest', 'Middle', 'Lowest') %>% paste(., 'tertile'), 
       title = 'Trading age', col = c('black', 'blue', 'red'), bty = 'n')

assign(paste0('AvgReturnTS', i), recordPlot()) 
}

save(AvgReturnTS1, AvgReturnTS2, file = 'returnTS.rda')

# cum mean return
# backward -- based on your current age percentile, what was your historical cum mean return return
twmpret = clientdaily[account_date > '2012-01-01', list(
  age = age,
  account_date = account_date,
  firstobs = firstobs,
  ret = meanappret)] %>% merge(popweight)


m1 = twmpret[age>365 & age <5500, list(mret = mean(ret, na.rm = T)), by = age][order(age), mret]
m1wt = twmpret[age>365 & age <5500, list(mret = weighted.mean(ret, wt, na.rm = T)), by = age][order(age), plot(age, mret, type = 'l')]

m1 = twmpret[age>365 & age <5500, list(mret = mean(ret, na.rm = T)), by = age][order(age), mret]
m1wt = twmpret[age>365 & age <5500, list(mret = weighted.mean(ret, wt, na.rm = T)), by = age][order(age), plot(age, mret, type = 'l')]


# using last year return
twmpret = clientdaily[account_date > '2012-01-01', list(
  age = age,
  account_date = account_date,
  firstobs = firstobs,
  ret = raprofit365)] %>% merge(popweight)

par(mgp=c(1.5,0.5,0), xpd = F)
# average last-year return by age
twmpret[age>365 & age <5500, list(mret = mean(ret, na.rm = T)), by = age][order(age), plot(age, mret, type = 'l', xlab = 'Trading age', ylab = 'Average one-year relative log return')]

AvgYearReturn = recordPlot()

# average last-year return normalized to entry rate by age
twmpret[age>365 & age <5500, list(mret = weighted.mean(ret, wt, na.rm = T)), by = age][order(age), plot(age, mret, type = 'l', xlab = 'Trading age', ylab = 'One-year relative log return\nentry-mass-weighted average')]

AvgYearReturnNorm = recordPlot()

# using cum mean return
twmpret = clientdaily[firstobs > '2009-01-01', list(
  age = age,
  account_date = account_date,
  firstobs = firstobs,
  ret = meanappret)] %>% merge(popweight)

twmpret[age>365 & age <3200, list(mret = mean(ret, na.rm = T) * 365.2425), by = age][order(age), plot(age, mret, type = 'l', xlab = 'Trading age', ylab = 'Average annualized cumulative relative log return')]
AvgCumReturn = recordPlot()

twmpret[age>365 & age <3200, list(mret = weighted.mean(ret, wt, na.rm = T) * 365.2425), by = age][order(age), plot(age, mret, type = 'l', xlab ='Trading age', ylab = 'Annualized cumulative relative log return\nentry-mass-weighted average')]
AvgCumReturnNorm = recordPlot()

save(AvgYearReturn, AvgYearReturnNorm, AvgCumReturn, AvgCumReturnNorm, file = 'AvgReturnByAge.rda')

par(new = T)

# SMI[, plot(account_date, smidailyret, type = 'l', col = 'orange')]


xx = merge(temp[agepr >= 2/3, list(mret3 = mean(ret, na.rm = T)), by = account_date],
      temp[agepr < 2/3 & agepr > 1/3, list(mret2 = mean(ret, na.rm = T)), by = account_date]) %>% 
  merge(temp[agepr <= 1/3, list(mret1 = mean(ret, na.rm = T)), by = account_date]) %>%
  merge(SMI)

xx = xx[order(account_date)]


cov(xx[, c('mret1', 'mret2', 'mret3', 'smidailyret')])
```

```{r ReturnBeforeClosing, eval=T}
load('regtable.rda')
load('cl_transferin.rda')
load('optiontaders.rda')

regtable = regtable[!(
  client %in% unique(c(cl_transferin
                       # , cl_transferout
                       ))
  )]

if(!(exists('clientdaily2')|exists('clientdaily'))){
  load('clientdaily.rda')}


popweight = regtable[, list(wt = 1/(.N)), by = firstobs][order(firstobs)]
pops = merge(regtable, popweight, by = 'firstobs')

# remember to always use after 2010 data for age-return relationship -- because we do not have data before that

# 365-day return
# backward -- based on your current age percentile, what was your historical 365-day return

par(mgp=c(1.5,0.5,0), xpd = F)

popu = regtable[(lifetime >= 6 * 365.2425) & (lifetime < 7 * 365.2425) & !is.na(closing_date) &
                  !(client %in% optiontaders)]$client
temp = clientdaily[account_date >= '2009-01-01' & client %in% popu] %>% merge(popweight, by = 'firstobs')
temp[, timebeforeclosing := account_date - closing_date]
tempplot = temp[, list(mret = mean(raprofit365, na.rm = T)),
                by = c('timebeforeclosing')][order(timebeforeclosing)]
tempplot[550:length(mret), plot(timebeforeclosing, mret, type = 'l', xlab = 'Time before exit', ylab = 'Average one-year relative log return')]


popu = regtable[(lifetime >= 5 * 365.2425) & (lifetime < 6 * 365.2425) & !is.na(closing_date) &
                  !(client %in% optiontaders)]$client
temp = clientdaily[account_date >= '2009-01-01' & client %in% popu] %>% merge(popweight, by = 'firstobs')
temp[, timebeforeclosing := account_date - closing_date]
tempplot = temp[, list(mret = mean(raprofit365, na.rm = T)),
                by = c('timebeforeclosing')][order(timebeforeclosing)]
tempplot[550:length(mret), lines(timebeforeclosing, mret, col = 'blue')]

popu = regtable[(lifetime >= 4 * 365.2425) & (lifetime < 5 * 365.2425) & !is.na(closing_date) &
                  !(client %in% optiontaders)]$client
temp = clientdaily[account_date >= '2009-01-01' & client %in% popu] %>% merge(popweight, by = 'firstobs')
temp[, timebeforeclosing := account_date - closing_date]
tempplot = temp[, list(mret = mean(raprofit365, na.rm = T)),
                by = c('timebeforeclosing')][order(timebeforeclosing)]
tempplot[550:length(mret), lines(timebeforeclosing, mret, col = 'red')]

legend('topleft', col = c('black', 'blue', 'red'), legend = c('Between 6 and 7 years', 'Between 5 and 6 years', 'Between 4 and 5 years'), title = 'Exit time', lty = 1, bty = 'n')

# save(AvgReturnTS1, AvgReturnTS2, file = 'returnTS.rda')
```

```{r MassTroughtime, eval=T}
load('regtable.rda')

regtable = regtable[!(
  client %in% unique(c(cl_transferin
                       , cl_transferout
                       ))
  ), list(
    firstobs = firstobs,
    closing_date = closing_date,
    lastobs = lastobs
  )]

  
popweight = regtable[, list(wt = 1/(.N)), by = firstobs][order(firstobs)]
pops = merge(regtable, popweight)

masstable = merge(pops[, list(ent = .N, entwt = sum(wt)), by = firstobs], 
                pops[, list(exit = .N, exitwt = sum(wt)), by = closing_date], 
                by.x = 'firstobs', by.y = 'closing_date', all = T
            )[is.finite(firstobs)][order(firstobs)] %>% 
  merge(data.frame(firstobs = seq.Date(min(regtable$firstobs), max(regtable$lastobs), 1)), 
        all = T)
masstable[is.na(masstable)] = 0

masstable[, ':='(
  no_traders = cumsum(ent-exit),
  no_traderswt = cumsum(entwt-exitwt)
  )]

par(mgp=c(1.5,0.5,0), xpd = F)
masstable[ ,plot(firstobs, no_traders, type = 'l', 
     xlab = 'Calendar time', ylab = 'Trading mass (Number of traders)', bty = 'l',
     xaxs = 'i', yaxs = 'i',
     ylim = c(0, tail(no_traders, 1)))]

no_traders = recordPlot()
plot.new()

masstable[plot(firstobs, no_traderswt, type = 'l', 
     xlab = 'Calendar time', ylab = 'Trading mass (Norm. number of traders)', bty = 'l',
     xaxs = 'i', yaxs = 'i',
     ylim = c(0, tail(no_traderswt, 1)))]

no_traderswt = recordPlot()
plot.new()


masstable[plot(firstobs, 
               rollmean(exitwt, 365, na.rm = T, na.pad = T, align = 'left'),
     xlab = 'Calendar time', ylab = 'Trading mass (Norm. number of traders)', bty = 'l',
     xaxs = 'i', yaxs = 'i', type = 'l')]



# 
# save(rouentry, no_traders, no_traderswt, file = 'rouentry.rda')
# save(masstbl, file = 'masstbl.rda')

# save(pops, file = 'pops.rda')


# we have to normalize to entry rate, because in the model the entry rate is constant and in data not!
regtable$firstobs %>% table %>% plot(tick = F, ylab = 'No. new accounts')
axis(side = 2, labels = F)

rouentry = recordPlot()
plot.new()

masstbl = data.table(date_trans = seq.Date(min(regtable$firstobs, na.rm = T), max(regtable$lastobs, na.rm = T), 15))

masstbl[, ':='(no_traders =  NA, no_traderswt = NA)]


# xx[order(closing_date)][, fr := rollsum(N,550, na.pad = T, na.rm = T)/rollmean(no_traders,550, na.pad = T, na.rm = T)][, plot(closing_date, fr)]

for (i in 1:NROW(masstbl)){
  # pick a date
datesel = masstbl[i, date_trans]
 temp = pops[
  (is.na(closing_date) | closing_date >= datesel) & datesel >= firstobs
  ]
masstbl$no_traderswt[i] = temp$wt %>% sum
masstbl$no_traders[i] = temp %>% NROW
}





# xx = merge(regtable[, .N, by = closing_date][order(closing_date)],masstblfull ,
#            by.x = 'closing_date', by.y = 'date_trans', all.y = T)
# 
# 
# clientdaily[, plot(account_date, raprofit365, type = 'l', axes = F, ann=F
#                  , xlim=c('2009-06-01', '2017-07-01') %>% as.Date, col = 'red')]
# axis(4, col = 'red')
# par(new=T)
# xx[, plot(closing_date, 
#           rollsum(N, 365, na.rm = T, na.pad = T, align = 'left')/rollmean(ttln, 365, na.rm = T, na.pad = T, align = 'left'), col = 'black', type = 'l', ylab = '', ann=F, xlim=c('2009-06-01', '2017-07-01') %>% as.Date)]
# 
# legend('bottomright', lty = 1, legend = c('Exit rate over the next year', 'Avg excess log retrun SQ-wide \nover the previous year'), col = c('black', 'red'), bty = 'n')

```

```{r massdistbyage, eval=T}
load('regtable.rda')

regtable = regtable[!(
  client %in% unique(c(cl_transferin
                       ))
  )]

ncnt = 800

avgcnts = list()

datesel = '2018-12-31' %>% as.Date

popus = regtable[, list(
  client = client,
  firstobs = firstobs,
  lastobs = lastobs,
  closing_date = closing_date,
  trage = datesel - firstobs
)]

popu = popus[trage >= 0 & (is.na(closing_date) | closing_date >= datesel)]

popu[, exit := (!is.na(closing_date)) & closing_date <= datesel + tw]

avgcnt = merge(popus[, list(ttlcnt = .N), by = trage], # ttlcnt - number of total entry for traders with that age, or calendar time
               popu[, list(cnt = .N, exitcnt = sum(exit)), by = trage], 
               # cnt - number of traders reamining on that day for that age
               all.y = T)[order(trage)][, pp := cnt/ttlcnt]

par(mgp=c(1.5,0.5,0), xpd = F)
clr = c('cadetblue4', 'orange', 'darkolivegreen2')
k = 550
temp = avgcnt[, list(n = sum(pp)), by = trage][order(trage), 
               list(trage, n = rollsum(n, k, na.pad = T)/k)]
                    
temp$n[1] = 1

temp$n[1:k] = temp[, approx(trage, n, xout = trage)$y]

temp[, plot(trage, n, bty = 'l', type ='l', 
                    xlab = 'Trading age (days)', ylab = 'Trading mass',
                    xlim = c(0, 5500), ylim = c(0,1), xaxs = 'i', yaxs = 'i')]

massbyage = recordPlot()

save(massbyage, file = 'massbyage.rda')
```

```{r massdist, eval=T}
load('regtable.rda')

regtable = regtable[!(
  client %in% unique(c(cl_transferin
                       ))
  )]

ncnt = 800

avgcnts = list()

tw = 180 # do they exit within the next tw days?

for (i in 1:length(pickdates)){
  # pick a date
datesel = pickdates[i]

popus = regtable[, list(
  client = client,
  firstobs = firstobs,
  lastobs = lastobs,
  closing_date = closing_date,
  trage = datesel - firstobs
)]

popu = popus[trage >= 0 & (is.na(closing_date) | closing_date >= datesel)]

popu[, exit := (!is.na(closing_date)) & closing_date <= datesel + tw]

avgcnt = merge(popus[, list(ttlcnt = .N), by = trage], # ttlcnt - number of total entry for traders with that age, or calendar time
               popu[, list(cnt = .N, exitcnt = sum(exit)), by = trage], 
               # cnt - number of traders reamining on that day for that age
               all.y = T)[order(trage)][, pp := cnt/ttlcnt]

avgcnts[[i]] = avgcnt
}


par(mgp=c(1.5,0.5,0), xpd = F)
clr = c('cadetblue4', 'orange', 'darkolivegreen2')
avgcnts[[1]][, trage %>% as.numeric %>% 
               density(cut = -12000/as.numeric(max(trage)), weights = (pp)/sum(pp)) %>% 
               plot(ylim = c(0.00015, 0.00027), xlim = c(0, 5000), bty = 'l', 
                    xlab = 'Trading age (days)', ylab = 'Density', main = '', col = clr[1])]
avgcnts[[2]][, trage %>% as.numeric %>% 
               density(cut = -12000/as.numeric(max(trage)), weights = (pp)/sum(pp)) %>% 
               lines(col = clr[2])]
avgcnts[[3]][, trage %>% as.numeric %>% 
               density(cut = -12000/as.numeric(max(trage)), weights = (pp)/sum(pp)) %>% 
               lines(col = clr[3])]

legend('bottomleft', legend = pickdates, lty = 1, col = clr,
       title = 'Calendar time', bty = 'n', xpd = T)

massdistwt = recordPlot()


avgcnts[[1]][, trage %>% as.numeric %>% density(cut = 0, weights = (cnt)/sum(cnt), n = (trage %>% range %>% diff %>% as.numeric)+1)] -> xx1

avgcnts[[2]][, trage %>% as.numeric %>% density(cut = 0, weights = (cnt)/sum(cnt), n = (trage %>% range %>% diff %>% as.numeric)+1)] -> xx2

avgcnts[[3]][, trage %>% as.numeric %>% density(cut = 0, weights = (cnt)/sum(cnt), n = (trage %>% range %>% diff %>% as.numeric)+1)] -> xx3

xx1 %>% plot(ylim = c(0, 0.0005), xlim = c(0, 5000), bty = 'l', 
                    xlab = 'Trading age (days)', ylab = 'Density', main = '')
xx2 %>% lines(col = 'red')
xx3 %>% lines(col = 'blue')


legend('topright', legend = pickdates, lty = 1, col = c('black', 'red', 'blue'),
       title = 'Calendar time', bty = 'n')

massdist = recordPlot()



# mass of exit traders
par(mgp=c(1.5,0.5,0), xpd = F)
k = 365
clr = c('black', 'gray35', 'gray70')
avgcnts[[1]][, agediff := c(0,diff(trage))][, plot(trage, rollsum(exitcnt/ttlcnt, k, na.pad = T)/rollsum(agediff, k, na.pad = T), bty = 'l', type ='l', 
                    xlab = 'Trading age (days)', ylab = 'Exiting mass',
                    xlim = c(0, 4900),ylim = c(0, 0.017), xaxs = 'i', yaxs = 'i')]
avgcnts[[2]][, agediff := c(0,diff(trage))][, lines(trage, rollsum(exitcnt/ttlcnt, k, na.pad = T)/rollsum(agediff, k, na.pad = T), col = clr[2])]
avgcnts[[3]][, agediff := c(0,diff(trage))][, lines(trage, rollsum(exitcnt/ttlcnt, k, na.pad = T)/rollsum(agediff, k, na.pad = T), col = clr[3])]
legend('bottom', legend = pickdates, lty = 1, col = clr,
       title = 'Calendar time', bty = 'n', xpd = T)

massexitdist = recordPlot()

# exit likelihood by age
avgcnts[[1]][, trage %>% as.numeric %>% density(cut = 0, weights = (exitcnt)/sum(exitcnt), n = (trage %>% range %>% diff %>% as.numeric) +1)] -> xxe1
avgcnts[[2]][, trage %>% as.numeric %>% density(cut = 0, weights = (exitcnt)/sum(exitcnt), n = (trage %>% range %>% diff %>% as.numeric) +1)] -> xxe2
avgcnts[[3]][, trage %>% as.numeric %>% density(cut = 0, weights = (exitcnt)/sum(exitcnt), n = (trage %>% range %>% diff %>% as.numeric) +1)] -> xxe3



plot(xx1$x, xxe1$y/xx1$y*sum(avgcnts[[1]]$exitcnt)/sum(avgcnts[[1]]$cnt),
     type = 'l', xlab = 'Trading age (days)', ylab = 'Exit likelihood',
     xlim = c(0, 5200), ylim = c(0,0.033), xaxs = 'i', yaxs = 'i', bty = 'l', col = clr[1])
lines(xx2$x, xxe2$y/xx2$y*sum(avgcnts[[2]]$exitcnt)/sum(avgcnts[[2]]$cnt), col = clr[2])
lines(xx3$x, xxe3$y/xx3$y*sum(avgcnts[[3]]$exitcnt)/sum(avgcnts[[3]]$cnt), col = clr[3])
legend('bottom', legend = pickdates, lty = 1, col = clr,
       title = 'Calendar time', bty = 'n', xpd = T)

exitlikelidist = recordPlot()

save(massdist, massdistwt, massexitdist, exitlikelidist, file = 'massdist.rda')
```

```{r exitlikeligivenT, eval=T}
# load('regtable.rda')
# regtable = regtable[!(
#   client %in% unique(c(cl_transferin, cl_transferout))
#   )]

load('pops.rda')
nAgeGroups = 8

par(mgp=c(1.5,0.5,0), xpd = F)

tw = 180

exitliks = list()

exitlikswt = list()

for (i in 1:length(pickdates)){
  # pick a date
datesel = pickdates[i]

popu = pops[, trage := datesel - firstobs][trage >= 0 & (is.na(closing_date) | closing_date >= datesel)]


# exit within the selected time window tw?
popu[, exit := (!is.na(closing_date)) & closing_date <= datesel + tw]

popu[, agerank := frank(trage)]

popu[, agegroup := ceiling(agerank/(.N) * nAgeGroups)]


temp = popu[, list(exits = sum(exit*wt), tots = sum(wt)), by = trage][order(trage)]
exitmasswt =  temp[, list(
  age = rollmean(trage, 1500),
  exitm = rollsum(exits, 1500),
  totsm = rollsum(tots, 1500)
)]

exitmasswt[, plot(age, exitm, type = 'l')]


temp = popu[, list(exits = sum(exit), tots = .N), by = trage][order(trage)]
exitmass =  temp[, list(
  age = rollmean(trage, 1500),
  exitm = rollsum(exits, 1500),
  totsm = rollsum(tots, 1500)
)]

exitmass[, plot(age, exitm/totsm, type = 'l', ylim = c(0, 0.023))]

exitliks[[i]] = popu[, list(exits = sum(exit),
                            tots = .N), by = agegroup][order(agegroup)]
exitliks[[i]][, exitlik := exits/tots]
exitliks[[i]]$ageupper = quantile(popu$trage, (0:nAgeGroups)/nAgeGroups) %>% rollmean(2)


exitlikswt[[i]] = popu[, list(exits = sum(exit*wt),
                            tots = sum(wt)), by = agegroup][order(agegroup)]
exitlikswt[[i]][, exitlik := exits/tots]
exitlikswt[[i]]$ageupper = quantile(popu$trage, (1:nAgeGroups)/nAgeGroups)
}

par(mgp=c(1.5,0.5,0), xpd = F)



allr = lapply(exitlikswt, FUN = function(x) x$exitlik) %>% unlist
exitlikswt[[1]][, plot(ageupper, exitlik, type = 'l'
          , xlim = c(0,6000), ylim = range(allr)
          , xlab = 'Trading age $t$', 
          ylab = paste0('Exit likelihood')
          , bty = 'l'
          )]
exitlikswt[[2]][, lines(ageupper, exitlik, col = 'red')]
exitlikswt[[3]][, lines(ageupper, exitlik, col = 'blue')]


allr = lapply(exitliks, FUN = function(x) x$exitlik) %>% unlist
exitliks[[1]][, plot(ageupper, exitlik, type = 'l'
          , xlim = c(0,6000), ylim = range(allr)
          , xlab = 'Trading age $t$', 
          ylab = paste0('Exit likelihood')
          , bty = 'l'
          )]
exitliks[[2]][, lines(ageupper, exitlik, col = 'red')]
exitliks[[3]][, lines(ageupper, exitlik, col = 'blue')]
legend('topleft', legend = pickdates, lty = 1, col = c('black', 'red', 'blue'),
       title = 'Calendar time $T$', bty = 'n')
```

```{r exitgivenRT, eval=F}
# procrastination

if(!(exists('clientdaily2')|exists('clientdaily'))){
  load('clientdaily.rda')}

clr = c('deepskyblue4', 'orange2', 'green4')

rn = 3
par(mgp=c(1.5,0.5,0), xpd = F)

nAgeGroups = 6

pltexitgivenT = list()
for (i in 1:length(pickdates)){
  # pick a date
datesel = pickdates[i]

gc()
subsample = clientdaily[account_date > datesel-90 & account_date < datesel+90, list(
  client = client,
  account_date = account_date,
  firstobs = firstobs,
  lastobs = lastobs,
  closing_date = closing_date,
  trage = datesel - firstobs,
  raprofit = raprofit365
)][trage >= 365 & (is.na(closing_date) | closing_date >= datesel)]
gc()

returntplot = subsample[, list(
  closing_date = closing_date,
  trage = trage,
  raprofit = raprofit[which.min(abs(account_date-datesel))],
  account_date = account_date[which.min(abs(account_date-datesel))]), by = client]

# exit within the selected time window tw?
returntplot[, exit := (!is.na(closing_date)) & closing_date <= datesel + tw]

returntplot[, agegroup := ceiling(frank(trage)/(.N) * nAgeGroups)]
returntplot[, rgroup := ceiling(frank(raprofit)/(.N) * rn)]

# count exit number and total number in each age-return cohort
temp = returntplot[, list(
  cnt = .N
), by = c('agegroup', 'rgroup', 'exit')][order(agegroup, rgroup)] %>% 
  spread(exit, cnt)
names(temp)[3:4] = c('remain','exit')
temp[, ttlcnt := remain + exit][, exitlikli := exit/ttlcnt]

as = returntplot[, list(as = median(trage, na.rm = T)), by = agegroup]$as %>% sort

yrg = range(temp$exitlikli)

temp[rgroup == 1, plot(as[agegroup], exitlikli, 
          type='l', 
          # xlim =c(-0.74, 0.2),
          ylim = yrg,
          ylab = 'Exit likelihood', xlab = 'Trading age (days)', yaxs='i', bty = 'l', col = clr[1])
     ]

temp[rgroup == 2, lines(as[agegroup], exitlikli, col = clr[2])]

temp[rgroup == 3, lines(as[agegroup], exitlikli, col = clr[3])]

legend('topright', legend = c('Lowest tertile', 'Middle tertile','Highest tertile'), lty = 1, col = clr,
       title = 'One-year trading return', bty = 'n', xpd = T)

assign(paste0('pltexitgivenRT',i), recordPlot())
plot.new()

mtext(datesel,side=1, line = 4, cex = 1)
}

save(pltexitgivenRT1, pltexitgivenRT2, pltexitgivenRT3, file = 'pltexitgivenRT.rda')
```

```{r exitgivenAgeT, eval=F}
# procrastination

rn = 8

nAgeGroups = 3

tw = 365

clr = c('deepskyblue4', 'orange2', 'green4')

pltexitgivenT = list()
for (i in 1:length(pickdates)){
  # pick a date
datesel = pickdates[i]

gc()
subsample = clientdaily[account_date > datesel-90 & account_date < datesel+90, list(
  client = client,
  account_date = account_date,
  firstobs = firstobs,
  lastobs = lastobs,
  closing_date = closing_date,
  trage = datesel - firstobs,
  raprofit = raprofit365 #meanappret
)][trage >= 0 & (is.na(closing_date) | closing_date >= datesel)]
gc()

returntplot = subsample[, list(
  closing_date = closing_date,
  trage = trage,
  raprofit = raprofit[which.min(abs(account_date-datesel))],
  account_date = account_date[which.min(abs(account_date-datesel))]), by = client]

# exit within the selected time window tw?

returntplot[, exit := (!is.na(closing_date)) & closing_date <= datesel + tw]

returntplot[, agegroup := cut(trage %>% as.numeric(), breaks = c(0, 550, 1500, 3000, Inf), labels = F)
              # ceiling(frank(trage)/(.N) * nAgeGroups)
            ]
returntplot[, rgroup := ceiling(frank(raprofit)/(.N) * rn)]

# rrange1 = -2.1
# rrange2 = 1.1
# nr = 20
# 
# returntplot[trage < 500 & exit == T, (
#   raprofit365 %>% density(from = rrange1, to = rrange2, n = nr, na.rm = T))$y * (.N)] -> xxe1
# returntplot[trage < 500, (
#   raprofit365 %>% density(from = rrange1, to = rrange2, n = nr, na.rm = T))$y * (.N)] -> xx1
# 
# returntplot[trage >= 500 & trage <= 2000 & exit == T, (
#   raprofit365 %>% density(from = rrange1, to = rrange2, n = nr, na.rm = T))$y * (.N)] -> xxe2
# returntplot[trage >= 500 & trage <= 2000, (
#   raprofit365 %>% density(from = rrange1, to = rrange2, n = nr, na.rm = T))$y * (.N)] -> xx2
# 
# returntplot[trage >= 3000 & exit == T, (
#   raprofit365 %>% density(from = rrange1, to = rrange2, n = nr, na.rm = T))$y * (.N)] -> xxe3
# returntplot[trage >= 3000, (
#   raprofit365 %>% density(from = rrange1, to = rrange2, n = nr, na.rm = T))$y * (.N)] -> xx3
# 
# 
# 
# par(mgp=c(1.5,0.5,0), xpd = F)
# plot(seq(rrange1, rrange2, length.out = nr), xxe2/xx2, 
#      col = clr[2], type = 'l', ylim = c(0, 0.082), xlab = '1-year return', ylab = 'Exit likelihood', bty = 'l')
# lines(seq(rrange1, rrange2, length.out = nr), xxe1/xx1, col = clr[1])
# lines(seq(rrange1, rrange2, length.out = nr), xxe3/xx3, col = clr[3])

# count exit number and total number in each age-return cohort
temp = returntplot[, list(
  cnt = .N
), by = c('agegroup', 'rgroup', 'exit')][order(agegroup, rgroup)] %>%
  spread(exit, cnt)
names(temp)[3:4] = c('remain','exit')
temp[, ttlcnt := remain + exit][, exitlikli := exit/ttlcnt]

rs = returntplot[, list(rs = median(raprofit, na.rm = T)), by = rgroup]$rs %>% sort

yrg = range(temp$exitlikli)

par(mgp=c(1.5,0.5,0), xpd = F)

temp[agegroup == 2, plot(rs[rgroup], exitlikli,
          type='l',
          # xlim =c(-0.74, 0.2),
          ylim = c(0,0.085),
          ylab = 'Exit likelihood', xlab = 'One-year trading return', yaxs='i', bty = 'l', col = clr[1])
     ]

temp[agegroup == 3, lines(rs[rgroup], exitlikli, col = clr[2])]

temp[agegroup == 4, lines(rs[rgroup], exitlikli, col = clr[3])]


legend('topright', legend = c('550 - 1500', '1500 - 3000', '> 3000'), lty = 1, col = clr,
       title = 'Trading age (days)', bty = 'n', xpd = T)

# mtext(datesel,side=1, line = 4, cex = 1)

assign(paste0('pltexitgivenageT',i), recordPlot())

plot.new()
}

save(pltexitgivenageT1, pltexitgivenageT2, pltexitgivenageT3, file = 'pltexitgivenT.rda')
```

```{r exitgivenR, eval=F}
load('regtable.rda')
regtable = regtable[!(
  client %in% unique(c(cl_transferin, cl_transferout))
  )]

# load('pops.rda')
nAgeGroups = 8

par(mgp=c(1.5,0.5,0), xpd = F)

tw = 180

exitliks = list()

exitlikswt = list()

for (i in 1:length(pickdates)){
  # pick a date
  
  datesel = pickdates[i]
  
  popu = regtable[, trage := datesel - firstobs][trage >= 0 & (is.na(closing_date) | closing_date >= datesel)]
  
  popu[, exit := (!is.na(closing_date)) & closing_date <= datesel + tw]
  
  gc()
  subsample = clientdaily[account_date > datesel-90 & account_date < datesel+90][client %in% popu$client]
  gc()
  
  subsample = subsample[, list(
  raprofit365 = raprofit365[which.min(abs(account_date-datesel))],
  account_date = account_date[which.min(abs(account_date-datesel))]), by = client]
  
  returntplot = merge(popu, na.omit(subsample))
  
  returntplot[, agegroup := ceiling(frank(trage)/(.N) * nAgeGroups)]
  
  returntplot[, rgroup := ceiling(frank(raprofit365)/(.N) * rn)]


# exit within the selected time window tw?
popu[, exit := (!is.na(closing_date)) & closing_date <= datesel + tw]

popu[, agerank := frank(trage)]

popu[, agegroup := ceiling(agerank/(.N) * nAgeGroups)]


# temp = popu[, list(exits = sum(exit*wt), tots = sum(wt)), by = trage][order(trage)]
# exitmass =  temp[, list(
#   age = rollmean(trage, 1500),
#   exitm = rollsum(exits, 1500),
#   totsm = rollsum(tots, 1500)
# )]
# 
# exitmass[, plot(age, exitm, type = 'l')]


exitliks[[i]] = popu[, list(exits = sum(exit),
                            tots = .N), by = agegroup][order(agegroup)]
exitliks[[i]][, exitlik := exits/tots]
exitliks[[i]]$ageupper = quantile(popu$trage, (0:nAgeGroups)/nAgeGroups) %>% rollmean(2)


# exitlikswt[[i]] = popu[, list(exits = sum(exit*wt),
#                             tots = sum(wt)), by = agegroup][order(agegroup)]
# exitlikswt[[i]][, exitlik := exits/tots]
# exitlikswt[[i]]$ageupper = quantile(popu$trage, (1:nAgeGroups)/nAgeGroups)
}

par(mgp=c(1.5,0.5,0), xpd = F)



allr = lapply(exitlikswt, FUN = function(x) x$exitlik) %>% unlist




allr = lapply(exitliks, FUN = function(x) x$exitlik) %>% unlist
exitliks[[1]][, plot(ageupper, exitlik, type = 'l'
          , xlim = c(0,6000), ylim = range(allr)
          , xlab = 'Trading age $t$', 
          ylab = paste0('Exit likelihood')
          , bty = 'l'
          )]
exitliks[[2]][, lines(ageupper, exitlik, col = 'red')]
exitliks[[3]][, lines(ageupper, exitlik, col = 'blue')]
legend('topleft', legend = pickdates, lty = 1, col = c('black', 'red', 'blue'),
       title = 'Calendar time', bty = 'n')

#exit likelhood does look like model! :D
```

```{r avgreturn, eval=F}
load('regtable.rda')
rm(cl_retail, Closed_account, u.trans)
gc()
if(!(exists('clientdaily2')|exists('clientdaily'))){
  load('clientdaily.rda')
}




nAgeGroups = 25

avgreturns = list()

popweight = regtable[, list(wt = 1/(.N)), by = firstobs]

nroll = 365
# for (nroll in nrolls){
  # pick a return measurement
  pickr = paste0('raprofit', nroll) # 'meanappret'

# pickdates = '2018-12-31' %>% as.Date
for (i in 1:length(pickdates)){
  # pick a date
datesel = pickdates[i]

popu = regtable[datesel >= firstobs , list(
  client = client,
  firstobs = firstobs,
  lastobs = lastobs,
  closing_date = closing_date
)][is.na(closing_date) | closing_date >= datesel]

subsample = clientdaily[account_date > datesel-90 & account_date < datesel+90& is.finite(get(pickr))][client %in% popu$client]

subsample = subsample[, list(
  raprofit = get(pickr)[which.min(abs(account_date-datesel))],
  account_date = account_date[which.min(abs(account_date-datesel))]), by = client]

returntplot = merge(popu, na.omit(subsample)) %>% merge(popweight, by = 'firstobs')

returntplot[, trage := account_date - firstobs]
# avgreturns[[i]] = returntplot[, list(
#   meanr = mean(raprofit, na.rm = T)
# ), by = trage][order(trage)]

# avgreturns[[i]] = returntplot[, list(
#   meanr = weighted.mean(raprofit, wt)
# ), by = trage][order(trage)]

returntplot[trage > 365.2425*0, agegroup := ceiling(trage/365.2425*2)]

avgreturns[[i]] = returntplot[is.finite(agegroup), list(
 meanr = weighted.mean(raprofit, wt),
 trage = weighted.mean(trage, wt)
), by = agegroup][order(agegroup)]

}


  clr = c('black', 'gray35', 'gray70')

par(mgp=c(1.5,0.5,0), xpd = F)
# allr = lapply(avgreturns, FUN = function(x) x$meanr) %>% unlist
avgreturns[[1]][, plot( trage, meanr - mean(meanr), type = 'l'
          , xlim = c(0,6000), ylim = c(-.15, .04)
          , xlab = 'Trading age (days)'
          , ylab = 'Demeaned 365-day excess log return'
          , bty = 'l', col = clr[1])]
avgreturns[[2]][, lines( trage, meanr - mean(meanr), col = clr[2])]
avgreturns[[3]][, lines( trage, meanr - mean(meanr), col = clr[3])]
legend('bottom', legend = pickdates, lty = 1, col = clr,
       title = 'Calendar time', bty = 'n', xpd = T)


assign(paste0('avgreturn',nroll), recordPlot())
save(avgreturn365, file = 'avgreturn365.rda')
# plot.new()
# }


# save(avgreturn183, avgreturn365, avgreturn548, file = 'avgreturn.rda')

```

```{r retfolonecohort, eval=F}
load('optiontaders.rda')
load('cl_transferin.rda')

load('regtable.rda')
regtable = regtable[!(
  client %in% unique(c(cl_transferin))
  )]

if(!(exists('clientdaily2')|exists('clientdaily'))){
  load('clientdaily.rda')}

load('masstbl.rda')

# # mktvol = as.data.table(vol_spi) %>% setnames(c('SPI', 'SMI'))
# # mktvol$SPI = approx(1:NROW(mktvol), mktvol$SPI, 1:NROW(mktvol))$y
# # mktvol$SMI = approx(1:NROW(mktvol), mktvol$SMI, 1:NROW(mktvol))$y
# 
# # mktvol$date_trans = index(vol_spi) %>% as.Date
# 
# mktret = clientdaily[ , list(
#   mktret7 = mean(raprofit7, na.rm = T), 
#   mktret31 = mean(raprofit31, na.rm = T), 
#   mktret91 = mean(raprofit91, na.rm = T), 
#   mktret361 = mean(raprofit365, na.rm = T),
#   mktn = sum(raprofit365 %>% is.finite)
#   ), by = account_date]

dates = seq.Date(from = min(masstbl$date_trans), to = max(masstbl$date_trans), by = 1)


masstblcomp = data.table(
  date_trans = dates,
  ntraders = approx(x = masstbl$date_trans, y = masstbl$no_traders, method = 'constant', f = 0, xout = dates)$y) #%>% merge(mktvol)

par(mar=c(4,5,1.7,5), mgp = c(2, 0.8, 0))

pickage = c(4, 5, 6
            # , 7, 8
            ) * 365.2425 # pick an age

popweight = regtable[, list(wt = 1/(.N)), by = firstobs]

trsels = list()

for (k in 1:length(pickage)){ # pick an age
  
  i = pickage[k]
  popu = regtable[lifetime >= i & !(client %in% optiontaders)]$client
  temp = clientdaily[age <= i & account_date >= '2009-01-01' & client %in% popu] %>% merge(popweight, by = 'firstobs')

  
    
  gc()
  trsel = temp[, list(mret365wt = weighted.mean(raprofit365, wt, na.rm = T),
                      n = sum(raprofit365 %>% is.finite)
                      ), by = age][order(age)]
  trsels[[k]] = trsel
 
  print(k)
 }


par(mgp=c(1.5,0.5,0), xpd = F)

clr = c('cadetblue4', 'orange', 'darkolivegreen2')


trsels[[3]][365:NROW(trsel), plot(age, mret365wt, type = 'l', bty = 'l', xlab = 'Trading age (days)', ylab = 'Average one-year relative log return'
                                , ylim = c(-0.14, -0.04)
                                  , lwd = 1, col = clr[3])]
  trsels[[2]][365:NROW(trsel), lines(age, mret365wt, type = 'l', lwd = 1, col = clr[2])]
  trsels[[1]][365:NROW(trsel), lines(age, mret365wt, type = 'l', lwd = 1, col = clr[1])]
  # trsels[[4]][365:NROW(trsel), lines(age, mret365wt, type = 'l', lwd = 1)]
  legend('bottom', lty = 1, col = clr, 
         legend=c(4, 5, 6)%>% paste('Over', ., 'years'), title = 'Trader lifetime', bty = 'n')   
  
trreturn =  recordPlot()
  
save(trreturn, file = 'trreturn.rda')


# what about those who passed 4 years but not 6 years

  popu = regtable[(lifetime >= 4 * 365.2425) & (lifetime < 6 * 365.2425) & !(client %in% optiontaders)]$client
  temp = clientdaily[account_date >= '2009-01-01' & client %in% popu] %>% merge(popweight, by = 'firstobs')

  gc()
  
  par(mgp=c(1.5,0.5,0), xpd = F)
  
  trsels[[3]][365:NROW(age), plot(age, mret365wt, type = 'l', bty = 'l', xlab = 'Trading age (days)', ylab = 'Average one-year relative log return'
                                  , ylim = c(-0.2, -0.04)
                                  , lwd = 1, col = clr[3])]
  trsels[[1]][365:NROW(age), lines(age, mret365wt, type = 'l', lwd = 1, col = clr[1])]
  # trsel[is.na(closing_date), lines(age, mret365wt, type = 'l', lwd = 1, lty = 2)]
  
  temp[is.na(closing_date), 
       list(mret365wt = weighted.mean(raprofit365, wt, na.rm = T)), by = age][order(age)][
         365:1800, lines(age, mret365wt, type = 'l', lwd = 1, lty = 1)]
  
  temp[!is.na(closing_date), 
       list(mret365wt = weighted.mean(raprofit365, wt, na.rm = T)), by = age][order(age)][
         365:1800, lines(age, mret365wt, type = 'l', lwd = 1, lty = 3)]
  
   legend('bottomright', col = c('black', 'black', clr[c(1,3)]), 
         legend=c('Above 4 but below 6 and still trading', 'Exited after year 4 and before 6', c(4, 6) %>% paste('Over', ., 'years')), 
         title = 'Trader lifetime', bty = 'n', lty = c(1,3,1,1), xpd = T)   
  
trreturn46 =  recordPlot()
  
save(trreturn46, file = 'trreturn46.rda')

```

```{r retfolonecohortcum, eval=F}
load('optiontaders.rda')
load('cl_transferin.rda')

load('regtable.rda')
regtable = regtable[!(
  client %in% unique(c(cl_transferin))
  )]

if(!(exists('clientdaily2')|exists('clientdaily'))){
  load('clientdaily.rda')}

load('masstbl.rda')

dates = seq.Date(from = min(masstbl$date_trans), to = max(masstbl$date_trans), by = 1)


masstblcomp = data.table(
  date_trans = dates,
  ntraders = approx(x = masstbl$date_trans, y = masstbl$no_traders, method = 'constant', f = 0, xout = dates)$y) #%>% merge(mktvol)

par(mar=c(4,5,1.7,5), mgp = c(2, 0.8, 0))

pickage = c(4, 5, 6, 7, 8) * 364.2425 # pick an age

popweight = regtable[, list(wt = 1/(.N)), by = firstobs]

trselscum = list()

for (k in 1:length(pickage)){ # pick an age
  
  i = pickage[k]
  popu = regtable[lifetime >= i & !(client %in% optiontaders)]$client
  temp = clientdaily[age <= i & firstobs >= '2009-01-01' & client %in% popu] %>% merge(popweight, by = 'firstobs')

  
  gc()
  trsel = temp[, list(mretapp = mean(meanappret, na.rm = T),
                      mretappwt = weighted.mean(meanappret, wt, na.rm = T),
                      n = sum(raprofit365 %>% is.finite)
                      ), by = age][order(age)]
  trselscum[[k]] = trsel
 
  print(k)
 }


par(mgp=c(1.5,0.5,0), xpd = F)

clr = c('cadetblue4', 'orange', 'darkolivegreen2')


trselscum[[3]][365:NROW(trsel), plot(age, mretappwt * 365.2425, type = 'l', bty = 'l', xlab = 'Trading age (days)', ylab = 'Average annualized relative log return since entry'
                                  # , ylim = c(-1e-3, -2.5e-4)
                                  , lwd = 1, col = clr[3])]
  trselscum[[2]][365:NROW(trsel), lines(age, mretappwt * 365.2425, type = 'l', lwd = 1, col = clr[2])]
  trselscum[[1]][365:NROW(trsel), lines(age, mretappwt * 365.2425, type = 'l', lwd = 1, col = clr[1])]
  # trselscum[[4]][100:NROW(trsel), lines(age, mretappwt, type = 'l', lwd = 1)]
  legend('bottom', lty = 1, col = clr, 
         legend=c(5, 6, 7) %>% paste0('Over ', ., '-year experience'), title = 'Traders included', bty = 'n')   
  
trreturncum =  recordPlot()
  
save(trreturncum, file = 'trreturncum.rda')
```

```{r retquantilefolonecohortcum, eval=F}
load('optiontaders.rda')
load('cl_transferin.rda')

load('regtable.rda')
regtable = regtable[!(
  client %in% unique(c(cl_transferin))
  )]

# if(!(exists('clientdaily2')|exists('clientdaily'))){
#   load('clientdaily.rda')}

load('masstbl.rda'%>% paste0(datapath, .))

dates = seq.Date(from = min(masstbl$date_trans), to = max(masstbl$date_trans), by = 1)


masstblcomp = data.table(
  date_trans = dates,
  ntraders = approx(x = masstbl$date_trans, y = masstbl$no_traders, method = 'constant', f = 0, xout = dates)$y) #%>% merge(mktvol)

popweight = regtable[, list(wt = 1/(.N)), by = firstobs]

trselscum = list()

# gc()
# temp0 = merge(clientdaily[,list(client, account_date, firstobs, raprofit365, age)], popweight, by = 'firstobs')
# gc()


# temp0[is.finite(raprofit365), ':='(
#     retpr = ecdf(raprofit365)(raprofit365),
#     retprwt = ewcdf(raprofit365, weights = wt)(raprofit365)), by = account_date]
# 
# save(temp0, file = 'temp0.rda')

load('temp0.rda'%>% paste0(datapath, .))

# temp0 = temp0[firstobs >= '2009-01-01']
# temp0[is.finite(raprofit365), wtage := 1/(.N), by = c('account_date', 'age')]
# temp0[is.finite(raprofit365), ':='(
#     retprwtage = ewcdf(raprofit365, weights = wtage)(raprofit365)), by = account_date]
# gc()
# save(temp0, file = 'temp0.rda')

# & !(client %in% optiontaders)
pickage = c(2, 3.5, 5) * 364.2425 # pick an age

trselsplm = list()
ns = c()
for (k in 1:length(pickage)){ # pick an age
  
  i = pickage[k]
  popu = regtable[lifetime >= i & firstobs >= '2009-01-01']$client
  temp = temp0[age >= 365 & age <= i & account_date > '2009-12-31' & client %in% popu]
  ns = c(ns, temp$client %>% unique() %>% length())
  gc()
  
  trselsplm[[k]] = pdata.frame(temp[, c('client', 'account_date', 'age', 'retpr')], index=c('client', 'account_date'), row.names = F)
  trsel = temp[, list(medretq = median(retpr, na.rm = T),
                      medretqwt = weighted.median(retpr, wt, na.rm = T),
                      mretq = mean(retpr, na.rm = T),
                      conf1 = t.test(retpr)$conf.int[1],
                      conf2 = t.test(retpr)$conf.int[2], 
                      mretqwt = weighted.mean(retpr, wt, na.rm = T)
                      ), by = age][order(age)]
  trselscum[[k]] = trsel
 
  print(k)
 }


#exited after two years and before 6
  popu = regtable[lifetime >= 2 * 364.2425 & lifetime <= 5 * 364.2425 & is.finite(closing_date) & firstobs >= '2009-01-01']$client
  temp = temp0[age >= 365 & account_date > '2009-12-31' & client %in% popu]
  
  trselsplm[[k+1]] = pdata.frame(temp[, c('client', 'account_date', 'age', 'retpr')], index=c('client', 'account_date'), row.names = F)
  
  gc()
  trsel = temp[, list(n=.N,
                      medretq = median(retpr, na.rm = T),
                      medretqwt = weighted.median(retpr, wt, na.rm = T),
                      mretq = mean(retpr, na.rm = T),
                      conf1 = t.test(retpr)$conf.int[1],
                      conf2 = t.test(retpr)$conf.int[2], 
                      mretqwt = weighted.mean(retpr, wt, na.rm = T)
                      ), by = age][order(age)]

clr = c('cadetblue4', 'orange', 'darkolivegreen2')
    
par(mgp=c(1.5,0.5,0), xpd = F)
   trselscum[[3]][1:NROW(trsel), plot(age, mretq, type = 'l', bty = 'l', xlab = 'Trading age (days)', ylab = 'Mean relative rank of one-year log return'
                                    , ylim = c(0.4, 0.498)
                                    , lwd = 1, col = clr[3])]
   
  trselscum[[3]][, polygon(x=c(age,rev(age)), y = c(conf1, rev(conf2)), col = adjustcolor(clr[3], 0.2), border = NA)]
   
     trselscum[[2]][1:NROW(trsel), lines(age, mretq, type = 'l', lwd = 1, col = clr[2])]
     trselscum[[2]][, polygon(x=c(age,rev(age)), y = c(conf1, rev(conf2)), col = adjustcolor(clr[2], 0.2), border = NA)]
     
    trsel[1:365, lines(age, mretq, type = 'l', lwd = 1)]
     trsel[1:365, polygon(x=c(age,rev(age)), y = c(conf1, rev(conf2)), col = adjustcolor('black', 0.2), border = NA)]
     
    trselscum[[1]][1:NROW(trsel), lines(age, mretq, type = 'l', lwd = 1, col = clr[1])]
     trselscum[[1]][, polygon(x=c(age,rev(age)), y = c(conf1, rev(conf2)), col = adjustcolor(clr[1], 0.2), border = NA)]
     legend('right', lty = 1, col = clr %>% c('black'), legend = 
              c(2, 3.5, 5) %>% paste('>', ., 'years') %>%
              c('> 2 and < 5 years') %>% 
              paste0(' (n = ', c(ns, trsel$n[365]),')'), title = 'Trading age at exit', bty = 'n', xpd = T)  
     
    trreturnquantile =  recordPlot()
    save(trreturnquantile, file = 'trreturnquantile.rda')


    
# when age is aligned, using plm/lm seems not make a difference 
xx11 = plm(retpr~age, data = trselsplm[[1]][trselsplm[[1]]$age < 365.2425*1.5,])
xx11%>% fixef %>% t.test
xx21 = plm(retpr~age, data = trselsplm[[2]][trselsplm[[2]]$age < 365.2425*1.5,])
xx21%>% fixef %>% t.test
xx31 = plm(retpr~age, data = trselsplm[[3]][trselsplm[[3]]$age < 365.2425*1.5,])
xx31%>% fixef %>% t.test
xx41 = plm(retpr~age, data = trselsplm[[4]][trselsplm[[4]]$age < 365.2425*1.5,])
xx41%>% fixef %>% t.test

xx12 = plm(retpr~age, data = trselsplm[[1]][trselsplm[[1]]$age >= 365.2425*1.5 & trselsplm[[1]]$age < 365.2425*2,])
xx12%>% fixef %>% t.test
xx22 = plm(retpr~age, data = trselsplm[[2]][trselsplm[[2]]$age >= 365.2425*1.5 & trselsplm[[2]]$age < 365.2425*2,])
xx22%>% fixef %>% t.test
xx32 = plm(retpr~age, data = trselsplm[[3]][trselsplm[[3]]$age >= 365.2425*1.5 & trselsplm[[3]]$age < 365.2425*2,])
xx32%>% fixef %>% t.test
xx42 = plm(retpr~age, data = trselsplm[[4]][trselsplm[[4]]$age >= 365.2425*1.5 & trselsplm[[4]]$age < 365.2425*2,])
xx42%>% fixef %>% t.test


xx23 = plm(retpr~age, data = trselsplm[[2]][trselsplm[[2]]$age >= 365.2425*2 & trselsplm[[2]]$age < 365.2425*3.5,])
xx23%>% fixef %>% t.test
xx33 = plm(retpr~age, data = trselsplm[[3]][trselsplm[[3]]$age >= 365.2425*2 & trselsplm[[3]]$age < 365.2425*3.5,])
xx33%>% fixef %>% t.test

xx34 = plm(retpr~age, data = trselsplm[[3]][trselsplm[[3]]$age >= 365.2425*3.5 & trselsplm[[3]]$age < 365.2425*5,])
xx34%>% fixef %>% t.test


# when age is aligned, using plm/lm seems not make a difference 
xx11t = plm(retpr~age, data = trselsplm[[1]][trselsplm[[1]]$age < 365.2425*1.5,], effect = 'time')
xx11t %>% fixef %>% t.test

xx21t = plm(retpr~age, data = trselsplm[[2]][trselsplm[[2]]$age < 365.2425*1.5,], effect = 'time')
xx21t %>% fixef %>% t.test

xx31t = plm(retpr~age, data = trselsplm[[3]][trselsplm[[3]]$age < 365.2425*1.5,], effect = 'time')
xx31t %>% fixef %>% t.test

xx41t = plm(retpr~age, data = trselsplm[[4]][trselsplm[[4]]$age < 365.2425*1.5,], effect = 'time')
xx41t %>% fixef %>% t.test


xx12t = plm(retpr~age, data = trselsplm[[1]][trselsplm[[1]]$age >= 365.2425*1.5 & trselsplm[[1]]$age < 365.2425*2,], effect = 'time')
xx12t %>% fixef %>% t.test

xx22t = plm(retpr~age, data = trselsplm[[2]][trselsplm[[2]]$age >= 365.2425*1.5 & trselsplm[[2]]$age < 365.2425*2,], effect = 'time')
xx22t %>% fixef %>% t.test

xx32t = plm(retpr~age, data = trselsplm[[3]][trselsplm[[3]]$age >= 365.2425*1.5 & trselsplm[[3]]$age < 365.2425*2,], effect = 'time')
xx32t %>% fixef %>% t.test

xx42t = plm(retpr~age, data = trselsplm[[4]][trselsplm[[4]]$age >= 365.2425*1.5 & trselsplm[[4]]$age < 365.2425*2,], effect = 'time')
xx42t %>% fixef %>% t.test


xx23t = plm(retpr~age, data = trselsplm[[2]][trselsplm[[2]]$age >= 365.2425*2 & trselsplm[[2]]$age < 365.2425*3.5,], effect = 'time')
xx23t %>% fixef %>% t.test

xx33t = plm(retpr~age, data = trselsplm[[3]][trselsplm[[3]]$age >= 365.2425*2 & trselsplm[[3]]$age < 365.2425*3.5,], effect = 'time')
xx33t %>% fixef %>% t.test

xx34t = plm(retpr~age, data = trselsplm[[3]][trselsplm[[3]]$age >= 365.2425*3.5 & trselsplm[[3]]$age < 365.2425*5,], effect = 'time')
xx34t %>% fixef %>% t.test



# mean(fixef(<yourmodel>)) mean intercept?

xx1 = plm(retpr~age, data = trselsplm[[1]])
xx2 = plm(retpr~age, data = trselsplm[[2]])
xx3 = plm(retpr~age, data = trselsplm[[3]])
# here age is not aligned, so it makes a difference to have individual effect
xx4 = plm(retpr~age, data = trselsplm[[4]])


   trselscum[[3]][1:NROW(trsel), plot(age, mretq, type = 'l', bty = 'l', xlab = 'Trading age (days)', ylab = 'Mean relative rank of one-year log return'
                                    , ylim = c(0.435, 0.498)
                                    , lwd = 1, col = clr[3])]
   
  trselscum[[3]][, polygon(x=c(age,rev(age)), y = c(conf1, rev(conf2)), col = adjustcolor(clr[3], 0.2), border = NA)]
   
    trselscum[[2]][1:NROW(trsel), lines(age, mretq, type = 'l', lwd = 1, col = clr[2])]
     trselscum[[2]][, polygon(x=c(age,rev(age)), y = c(conf1, rev(conf2)), col = adjustcolor(clr[2], 0.2), border = NA)]
     
    trselscum[[1]][1:NROW(trsel), lines(age, mretq, type = 'l', lwd = 1, col = clr[1])]
     trselscum[[1]][, polygon(x=c(age,rev(age)), y = c(conf1, rev(conf2)), col = adjustcolor(clr[1], 0.2), border = NA)]
     legend('left', lty = 1, col = clr, 
         legend=c('2.0', 3.5, '5.0') %>% paste0('At least', ., 'years'), title = 'Tading age at exit', bty = 'n')  
    trreturnquantile =  recordPlot()


    # trselscum[[1]][1:NROW(trsel), lines(age, mretq, type = 'l', lwd = 1)]
    #  trselscum[[1]][, polygon(x=c(age,rev(age)), y = c(conf1, rev(conf2)), col = adjustcolor('black', 0.2), border = NA)]
     
    # trselscum[[2]][1:NROW(trsel), lines(age, mretq, type = 'l', lwd = 1)]
    # trselscum[[1]][1:NROW(trsel), lines(age, mretq, type = 'l', lwd = 1)]

    
    
trselscum[[6]][1:NROW(trsel), plot(age, medretqwt, type = 'l', bty = 'l', xlab = 'Trading age (days)', ylab = 'Average annualized relative log return since entry'
                                  , ylim = c(0.44, 0.51)
                                  , lwd = 1, col = clr[3])]
  trselscum[[5]][1:NROW(trsel), lines(age, medretqwt, type = 'l', lwd = 1, col = clr[2])]
  trselscum[[4]][1:NROW(trsel), lines(age, medretqwt, type = 'l', lwd = 1, col = clr[1])]
  trselscum[[3]][1:NROW(trsel), lines(age, medretqwt, type = 'l', lwd = 1)]
  trselscum[[2]][1:NROW(trsel), lines(age, medretqwt, type = 'l', lwd = 1)]
  trselscum[[1]][1:NROW(trsel), lines(age, medretqwt, type = 'l', lwd = 1)]
   


# trselscum[[4]][365:NROW(trsel), plot(age, mretqwtage, type = 'l', bty = 'l', xlab = 'Trading age (days)', ylab = 'Average annualized relative log return since entry'
#                                   , ylim = c(0.44, 0.50)
#                                   , lwd = 1, col = clr[3])]
#   trselscum[[3]][365:NROW(trsel), lines(age, mretqwtage, type = 'l', lwd = 1, col = clr[2])]
#   trselscum[[2]][365:NROW(trsel), lines(age, mretqwtage, type = 'l', lwd = 1, col = clr[1])]
#   trselscum[[1]][365:NROW(trsel), lines(age, mretqwtage, type = 'l', lwd = 1)]
#   legend('bottom', lty = 1, col = clr,
#          legend=c(2, 3, 4) %>% paste0('Over ', ., '-year experience'), title = 'Traders included', bty = 'n')
#   
  trselscum[[4]][1:NROW(trsel), plot(age, mretqwt, type = 'l', bty = 'l', xlab = 'Trading age (days)', ylab = 'Average annualized relative log return since entry'
                                    # , ylim = c(0.44, 0.497)
                                    , lwd = 1, col = clr[3])]
    trselscum[[3]][1:NROW(trsel), lines(age, mretqwt, type = 'l', lwd = 1, col = clr[2])]
    trselscum[[2]][1:NROW(trsel), lines(age, mretqwt, type = 'l', lwd = 1, col = clr[1])]
    trselscum[[1]][1:NROW(trsel), lines(age, mretqwt, type = 'l', lwd = 1)]
    # trselscum[[2]][1:NROW(trsel), lines(age, mretqwt, type = 'l', lwd = 1)]
    # trselscum[[1]][1:NROW(trsel), lines(age, mretqwt, type = 'l', lwd = 1)]
  legend('bottom', lty = 1, col = clr,
         legend=c(5, 6, 7) %>% paste0('Over ', ., '-year experience'), title = 'Traders included', bty = 'n')
  


par(mgp=c(1.5,0.5,0), xpd = F)


  
trreturnquantilewt =  recordPlot()
  

```

```{r trintfolonecohort, eval=F}
load('optiontaders.rda')


load('regtable.rda')
regtable = regtable[!(
  client %in% unique(c(cl_transferin))
  )]

load('masstbl.rda')

# mktvol = as.data.table(vol_spi) %>% setnames(c('SPI', 'SMI'))
# mktvol$SPI = approx(1:NROW(mktvol), mktvol$SPI, 1:NROW(mktvol))$y
# mktvol$SMI = approx(1:NROW(mktvol), mktvol$SMI, 1:NROW(mktvol))$y

# mktvol$date_trans = index(vol_spi) %>% as.Date

dates = seq.Date(from = min(masstbl$date_trans), to = max(masstbl$date_trans), by = 1)
masstblcomp = data.table(
  date_trans = dates,
  ntraders = approx(x = masstbl$date_trans, y = masstbl$no_traders, method = 'constant', f = 0, xout = dates)$y) #%>% merge(mktvol)

par(mar=c(4,5,1.7,5), mgp = c(2, 0.8, 0))

pickage = c(5, 10, 15) * 364.2425 # pick an age


sumtrdaily = u.trans2[!(client %in% optiontaders), list(sumtr = .N, sumchf = sum(vol_chf_trans, na.rm = T)), by = date_trans] %>% merge(masstblcomp, by = 'date_trans')

sumtrdaily[, ':='(sumtrpert = sumtr/ntraders, sumchfpert = sumchf/ntraders)]

for (k in 1:length(pickage)){ # pick an age
  i = pickage[k]
 popu = regtable[lifetime >= i & !(client %in% optiontaders), 'client']
 trsel = merge(trint[age <= i], popu) %>% merge(sumtrdaily, by = 'date_trans')
 
 # is this the right way to remove year effect?
 trsel[, ':='(trnorm = 1/sumtr
              , chfnorm = vol_chf_trans/sumchf
              )]
 
(table(trsel$age)/NROW(popu)) %>% plot(
  xaxt = 'n', bty = 'n', ylab = 'No. trades / person', xaxs = 'i', yaxs = 'i',
  xlim = range(trsel$age), ylim = c(0, 0.11))
 par(new = T)
 trsel$age %>% density(from = i/30, to = 0.96*i,
 na.rm = T) %>% plot( 
   col = 'red', lwd = 2, yaxt = 'n', bty = 'n', ylab = '', xlab = 'Trading age (days)',
        xaxs = 'i', xlim = range(trsel$age), ylim = c(0, 1.9/i), yaxs = 'i', main = '')
 axis(side = 4, col = 'red', col.axis = 'red')
 mtext("Density", side=4, line = 2, xpd = T, col = 'red')
 

trsel$age %>% density(
   na.rm = T, cut = 0, weights = (trsel$vol_chf_trans)/sum(trsel$vol_chf_trans, na.rm =T)
   , from = i/30, to = 0.96*i) %>% plot( 
   col = 'red', lwd = 2, bty = 'l', ylab = 'Density', xlab = 'Trading age (days)',
        xaxs = 'i', xlim = range(trsel$age), ylim = c(0, 1.9/i), yaxs = 'i', main = '')
 
assign(paste0('trintchf',k),recordPlot())
plot.new()


 trsel$age %>% density(
   na.rm = T, cut = 0, weights = (trsel$chfnorm)/sum(trsel$chfnorm, na.rm =T)
   , from = i/30, to = 0.96*i) %>% plot( 
   col = 'black', lwd = 2, bty = 'l', ylab = 'Density', xlab = 'Trading age (days)',
        xaxs = 'i', xlim = range(trsel$age), ylim = c(0, 3.3/i), yaxs = 'i', main = '')
 
 trsel$age %>% density(
   na.rm = T, cut = 0, weights = (trsel$trnorm)/sum(trsel$trnorm, na.rm =T)
   , from = i/30, to = 0.96*i) %>% lines( 
   col = 'red', lwd = 2, bty = 'l',
        xaxs = 'i', xlim = range(trsel$age))
 
 legend('topright', legend = c('Volume CHF', 'Count'), col = c('Black', 'Red'), lty = 1)
 
 
 if (k==3){
   brks = c(0, 2000, 2500, 3500, 4000, trsel$age %>% max)
   ser = trsel[, list(trnorm, chfnorm, age, agroup = cut(age, breaks = brks, labels = F)), 
               by = client] 
   
   grp = 1
   ser1 = ser[agroup == grp , list(
     trnorm = sum(trnorm, na.rm = T)/(brks[grp+1]- brks[grp]), 
     chfnorm = sum(chfnorm, na.rm = T)/(brks[grp+1]- brks[grp])
     ), by = client] %>% 
     merge(popu, all = T, by = 'client')
   ser1[is.na(ser1)] = 0

   
   grp = 3
     ser2 = ser[agroup == grp , list(
     trnorm = sum(trnorm, na.rm = T)/(brks[grp+1]- brks[grp]), 
     chfnorm = sum(chfnorm, na.rm = T)/(brks[grp+1]- brks[grp])
     ), by = client] %>% 
     merge(popu, all = T, by = 'client')
  ser2 = ser2[ , list(
     trnorm = mean(trnorm, na.rm = T), chfnorm = mean(chfnorm, na.rm = T)
     ), by = client]
  ser2[is.na(ser2)] = 0
  
  grp = 5
     ser3 = ser[agroup == grp, list(
     trnorm = sum(trnorm, na.rm = T)/(brks[grp+1]- brks[grp]), 
     chfnorm = sum(chfnorm, na.rm = T)/(brks[grp+1]- brks[grp])
     ), by = client] %>% 
     merge(popu, all = T, by = 'client')
  ser3 = ser3[ , list(
     trnorm = mean(trnorm, na.rm = T), chfnorm = mean(chfnorm, na.rm = T)
     ), by = client]
  ser3[is.na(ser3)] = 0
   
   ser1[, trnorm %>% density(cut = 0, n = 9999) %>% plot(
     xlim = c(0,0.00005), ylim = c(0,110000), xaxs = 'i', yaxs = 'i', xlab = 'Trading times')]
   ser2[, trnorm %>% density(cut = 0, n = 9999) %>% lines(col = 'red')]
   ser3[, trnorm %>% density(cut = 0, n = 9999) %>% lines(col = 'blue')]
   legend('topright', col = c('black', 'red', 'blue'), lty = 1, title = 'Trading age (days)', 
          legend = c(
            paste0(brks[1], ' -- ', brks[2]), paste0(brks[3], ' -- ', brks[4]), paste0(brks[5], ' -- ', brks[6])
            ))
   
   # t.test(ser2$trnorm, ser3$trnorm)
   
  ser1[, chfnorm %>% density(cut = 0, from = 0.00004, to = 0.002, n = 5000) %>% 
           plot(ylim = c(0,3630), xaxs = 'i', yaxs = 'i')]
   ser2[, chfnorm %>% density(cut = 0, n = 5000) %>% lines(col = 'red')]
   ser3[, chfnorm %>% density(cut = 0, n = 5000) %>% lines(col = 'blue')]
   legend('topright', col = c('black', 'red', 'blue'), lty = 1, title = 'Trading age (days)', 
          legend = c(
            paste0(brks[1], ' -- ', brks[2]), paste0(brks[3], ' -- ', brks[4]), paste0(brks[5], ' -- ', brks[6])
            ))
   
 }
 
 
 }

save(trintchf1, trintchf2, trintchf3, trintcnt1, trintcnt2, trintcnt3, file = 'trintfolonecohort.rda')
```

```{r trintquantile, eval=F}
load('regtable.rda')
regtable = regtable[!(
  client %in% unique(c(cl_transferin))
  )]
# this one looks cleaner than the roll-average method, and delivers the same message

# pick a time window to calculate trading intensity
tw = 361

nAgeGroups = 10

trintplots = list()


for (i in 1:length(pickdates)){
  # pick a date
datesel = pickdates[i]

trsel = trint[
  date_trans >= datesel - tw & date_trans <= datesel & (is.na(closing_date) | closing_date >= datesel), list(
  vol_chf_transttl = sum(vol_chf_trans, na.rm = T),
  countttl = .N
), by = client
]


popu = regtable[, list(
  client = client,
  firstobs = firstobs,
  lastobs = lastobs,
  closing_date = closing_date,
  trage = datesel - firstobs
)][trage >= 0 & (is.na(closing_date) | closing_date >= datesel)]

trintsel = merge(popu, trsel, all.x = T)
trintsel[, days := pmin(tw, trage)]

trintsel[, agerank := frank(trage)]

trintsel[, agegroup := ceiling(agerank/(.N) * nAgeGroups)]


trintplot = trintsel[, list(
  volttl = sum(vol_chf_transttl, na.rm = T), cnttl = sum(countttl, na.rm =T),
  nmass = .N, daysttl = sum(days, na.rm = T)
  ), by = agegroup][order(agegroup)]

trintplot$ageupper = quantile(trintsel$trage, (0:nAgeGroups)/nAgeGroups) %>% rollmean(2)

trintplots[[i]] = trintplot
}

par(mgp=c(1.5,0.5,0), xpd = F)


trintplots[[1]][, plot(ageupper, volttl/daysttl, type = 'l'
          , xlim = c(400,5500), ylim = c(0, 400),
          xlab = 'Trading age $t$ (days)', ylab = 'One-year trading intensity\nCHF/day/trader', bty = 'l'
          )]
trintplots[[2]][, lines(ageupper, volttl/daysttl, col = 'red')]
trintplots[[3]][, lines(ageupper, volttl/daysttl, col = 'blue')]
legend('topright', legend = pickdates, lty = 1, col = c('black', 'red', 'blue'),
       title = 'Calendar time $T$', bty = 'n')

trintplots1 = recordPlot()
plot.new()


# just one line for demonstration purposes
trintplots[[3]][, plot(ageupper, volttl/daysttl, type = 'l'
          , xlim = c(400,5500), ylim = c(0, 400),
          xlab = 'Trading age $t$ (days)', ylab = 'One-year trading intensity\nCHF/day/trader', bty = 'l', col = 'blue'  )]
trintplots3 = recordPlot()
plot.new()



trintplots[[1]][, plot(ageupper, cnttl/daysttl, type = 'l'
          , xlim = c(400,5500), ylim = c(0, 0.03),
          xlab = 'Trading age $t$ (days)', ylab = 'One-year trading intensity\ntimes/day/trader', bty = 'l'
          )]
trintplots[[2]][, lines(ageupper, cnttl/daysttl, col = 'red')]
trintplots[[3]][, lines(ageupper, cnttl/daysttl, col = 'blue')]

legend('topright', legend = pickdates, lty = 1, col = c('black', 'red', 'blue'),
       title = 'Calendar time $T$', bty = 'n')

trintplots2 = recordPlot()
plot.new()

save(trintplots1, trintplots2, trintplots3, file = 'trintplots.rda')
```

```{r trintrollav, eval=F}
# this one looks noisier than the quantile method, and delivers the same message

# pick a time window to calculate trading intensity
tw = 361

# a smooth time window
smoothtw = 500

nAgeGroups = 12

trintplots = list()


for (i in 1:length(pickdates)){
  # pick a date
datesel = pickdates[i]

trsel = trint[ # here you also have the option to select only buy or only sell orders
  date_trans >= datesel - tw & date_trans <= datesel & (is.na(closing_date) | closing_date >= datesel), list(
  vol_chf_transttl = sum(vol_chf_trans, na.rm = T),
  countttl = .N
), by = client]


popu = regtable[, list(
  client = client,
  firstobs = firstobs,
  lastobs = lastobs,
  closing_date = closing_date,
  trage = datesel - firstobs
)][trage >= 0 & (is.na(closing_date) | closing_date >= datesel) ]

trintsel = merge(popu, trsel, all.x = T)
trintsel[, days := pmin(tw, trage)]

trintplot = trintsel[, list(
  volttl = sum(vol_chf_transttl, na.rm = T), cnttl = sum(countttl, na.rm =T), daysttl = sum(days, na.rm = T)
  ), by = trage]

temp = data.table(trage = 1:max(popu$trage))

trintplot = merge(temp, trintplot, all.x = T)[order(trage)]

trintplot[, ':='(
  rsvolttl = rollsum(volttl, smoothtw, na.rm = T, align = 'center', fill = NA),
  rscnttl = rollsum(cnttl, smoothtw, na.rm = T, align = 'center', fill = NA),
  rsdaysttl = rollsum(daysttl, smoothtw, na.rm = T, align = 'center', fill = NA))
  ]

trintplots[[i]] = trintplot
}

par(mgp=c(1.5,0.5,0), xpd = F)


with(plot(trage, rsvolttl/rsdaysttl, type = 'l'
          , xlim = c(400,6000), ylim = c(0, 400)
          , xlab = 'Trading age $t$', ylab = 'Trading intensity\nCHF/day/trader', bty = 'l'
          ), data=trintplots[[1]])
with(lines(trage, rsvolttl/rsdaysttl, col = 'red'), data=trintplots[[2]])
with(lines(trage, rsvolttl/rsdaysttl, col = 'blue'), data=trintplots[[3]])
legend('topright', legend = pickdates, lty = 1, col = c('black', 'red', 'blue'),
       title = 'Calendar time $T$', bty = 'n')


with(plot(trage, rscnttl/rsdaysttl, type = 'l'
          , xlim = c(400,6000), ylim = c(0, 0.03)
          , xlab = 'Trading age $t$', ylab = 'Trading intensity\nCHF/day/trader', bty = 'l'
          ), data=trintplots[[1]])
with(lines(trage, rscnttl/rsdaysttl, col = 'red'), data=trintplots[[2]])
with(lines(trage, rscnttl/rsdaysttl, col = 'blue'), data=trintplots[[3]])
legend('topright', legend = pickdates, lty = 1, col = c('black', 'red', 'blue'),
       title = 'Calendar time $T$', bty = 'n')
```

```{r returntdist, eval=F}
gc()

# if(!exists('clientdaily')){load('clientdaily.rda')}

if(!(exists('clientdaily2')|exists('clientdaily'))){
  load('clientdaily2.rda')
  clientdaily = clientdaily2
  rm(clientdaily2)}

returntplots = list()

par(mgp=c(1.5,0.5,0), xpd = F)

for (i in 1:length(pickdates)){
  # pick a date
datesel = pickdates[i]

popu = regtable[, list(
  client = client,
  firstobs = firstobs,
  lastobs = lastobs,
  closing_date = closing_date,
  trage = datesel - firstobs
)][trage >= 0 & (is.na(closing_date) | closing_date >= datesel)]

subsample = clientdaily[account_date > datesel-90 & account_date < datesel+90][client %in% popu$client]

subsample = subsample[, list(
  raprofit365 = raprofit365[which.min(abs(account_date-datesel))],
  account_date = account_date[which.min(abs(account_date-datesel))]), by = client]

returntplot = merge(popu, na.omit(subsample))

series1 = returntplot[trage > quantile(trage, 4/5), raprofit365]
series2 = returntplot[trage < quantile(trage, 1/5), raprofit365]

series1 %>% density(na.rm = T, n=19999) %>% plot(
  main = '', xlab = paste0('361-day return $R$'),
  xlim = c(-1,1), ylim = c(0,4.9), yaxs='i', bty = 'l')
series2 %>% density(na.rm = T, n=19999)  %>% lines(col = 'red')


legend('topright', legend = 'Age $t$ highest 20\\%',
       lty = 1, col = 'black', xpd = T, bty = 'n', cex = 1)
legend('topright', legend = textlabel(series1 %>% na.omit), bty='n', cex = 1)

legend('topleft', legend = 'Age $t$ lowest 20\\%',
       lty = 1, col = 'red', xpd = T, bty = 'n', cex = 1)
legend('topleft', legend = textlabel(series2 %>% na.omit), bty='n', cex = 1)


p = ks.test(series1, series2)$p
p2 = t.test(series1, series2, na.action=na.omit, alternative = 'two.sided', mu = 0, paired = F, conf.level = 0.95)$p.value

cortest = cor.test(as.numeric(returntplot$trage), returntplot$raprofit365)

mtext(paste0('KS-test: $p=',formatC(p, digits = 3, format = 'f'),'$',funcstar(p),
             '\nt-test: $p=',formatC(p2, digits = 3, format = 'f'),'$',funcstar(p2),
             '\nCorr($t$, $R$): ', round(cortest$estimate, 3), funcstar(cortest$p.value)
             ),side=3, line = 0, cex = 1)

mtext(datesel,side=1, line = 4, cex = 1)
}
```  

```{r preparedaily, eval=F}
gc()

# if(!exists('clientdaily')){load('clientdaily.rda')}

if(!(exists('clientdaily2')|exists('clientdaily'))){
  load('clientdaily2.rda')
  clientdaily = clientdaily2
  rm(clientdaily2)}

clientdaily[, daystoexit := closing_date - account_date]
clientdaily[, cumr := daily_perf_excess %>% na.omit %>% cumsum, by = client]


ind1 = (clientdaily$account_date >= '2013-01-01') & (clientdaily$account_date <= '2013-12-31')
ind2 = (clientdaily$account_date >= '2014-01-01') & (clientdaily$account_date <= '2014-12-31')
ind3 = (clientdaily$account_date >= '2015-01-01') & (clientdaily$account_date <= '2015-12-31')
ind4 = (clientdaily$account_date >= '2016-01-01') & (clientdaily$account_date <= '2016-12-31')

ind5 = !clientdaily$gender # male
ind6 = clientdaily$gender # female

ind7 = clientdaily$TradesOptions == 0 #not trade options
ind8 = clientdaily$TradesOptions == 1

ind9 = clientdaily$nsec > 3 
ind10 = clientdaily$nsec <= 3 

ind11 = ind4 & ind5 & ind8 & ind10

# last observable account data right before exit
clientdaily[, exitpoint := daystoexit == min(daystoexit), by = client]
ind12 = clientdaily$exitpoint

lbls = c(
  'Year 2013',
  'Year 2014',
  'Year 2015',
  'Year 2016',
  'Male',
  'Female',
  'Option traders',
  'Non-option traders',
  '# securities > 3',
  '# securities <= 3',
  'Year 2016\nMale\nNon-option traders\n# securities <= 3',
  'Exit'
  )

```  

```{r returnremainexit, eval=F}
par(mgp=c(1.5,0.5,0), xpd = F)

rselect = 'lastr'
ageselect = 'maxage'

# for (i in 0:length(lbls)){
  for (i in 1:4){
  gc()
    indtemp = get(paste0('ind',i))
    
    lbl = lbls[i]
  
  temp = clientdaily[indtemp, list(
  avgage = mean(age, na.rm = T), maxage = max(age, na.rm = T),
  avgr = mean(raprofit365, na.rm = T), lastr = tail(raprofit365, 1),
  exit = sum(exitpoint, na.rm = T)
  ), by = client][get(rselect) %>% is.finite]
  
  temp = temp[get(ageselect) > quantile(get(ageselect),4/5)]
  
  series1 = temp[exit==0][[rselect]]
  series2 = temp[exit==1][[rselect]]

  
s1 = series1 %>% density(na.rm = T, n=19999) 

s2 = series2 %>% density(na.rm = T, n=19999)


s1 %>% plot(xlim=c(-1,1), main = '', 
            xlab = paste0('361-day return'), ylim = c(0, max(s1$y, s2$y) * 1.01), yaxs='i', bty = 'l')
s2 %>% lines(col='red')


legend('topright', legend = 'Remain',
       lty = 1, col = 'black', xpd = T, bty = 'n', cex = 0.8)
legend('topright', legend = textlabel(series1 %>% na.omit), bty='n', cex = 0.8)

legend('topleft', legend = 'Exit',
       lty = 1, col = 'red', xpd = T, bty = 'n', cex = 0.8)
legend('topleft', legend = textlabel(series2 %>% na.omit), bty='n', cex = 0.8)

p = ks.test(series1, series2)$p
p2 = t.test(series1, series2, na.action=na.omit, alternative = 'two.sided', mu = 0, paired = F, conf.level = 0.95)$p.value

cortest = cor.test(temp$exit, temp[[rselect]])

mtext(paste0('KS-test: $p=',formatC(p, digits = 3, format = 'f'),'$',funcstar(p),
             '\nt-test: $p=',formatC(p2, digits = 3, format = 'f'),'$',funcstar(p2),
             '\nCorr($1_{exit}$, $R$): ', round(cortest$estimate, 3), funcstar(cortest$p.value)
             ),side=3, line = 0, cex = 1)

mtext(lbl,side=1, line = 4, cex = 1)
}
```  

```{r performance, eval=F}
load('retcal.rda')

par(mar=c(4,5,1.7,2), mgp = c(2, 0.8, 0))

rtnmain = c('Return', 'Excess return (return exceeding SMI)')

age = retcala %>% rownames %>% as.numeric
for (i in 1:NCOL(retcala)){
  temp = retcala[,i]
  plot(age , temp %>% rollmean(7, na.rm = T, align = 'right', fill = NA), type = 'l', col = cols[1],
       ylim = c(-0.005,0.002),
       xlab = 'Age',
       ylab = 'Average daily log return\non account performance',
       main = rtnmain[i])
  for (x in 2:length(nrolls)){
    lines(age, temp %>% rollmean(nrolls[x], na.rm = T, align = 'right', fill = NA), col = cols[x])
    }
  legend('top', col = cols, legend = nrolls, lty = 1, title = 'Rolling window size (days)', horiz = T)
}


for (i in 1:NCOL(retcala)){
  temp = retcala[,i]
  plot(age , temp %>% rollsum(7, na.rm = T, align = 'right', fill = NA), type = 'l', col = cols[1],
       ylim = c(-0.5,0.3),
       xlab = 'Age',
       ylab = 'Log return on account performance\nover rolling window period',
       main = rtnmain[i])
  for (x in 2:length(nrolls)){
    lines(age, temp %>% rollsum(nrolls[x], na.rm = T, align = 'right', fill = NA), col = cols[x])
    }
  legend('top', col = cols, legend = nrolls, lty = 1, title = 'Rolling window size (days)', horiz = T)
}



cal = rownames(retcal) %>% as.Date

for (i in 1:NCOL(retcal)){
  temp = retcal[,i]
  plot(cal, temp %>% rollmean(7, na.rm = T, align = 'right', fill = NA), type = 'l', col = cols[1],
       ylim = c(-0.01,0.01),
       xlab = 'Calendar date',
       ylab = 'Average daily log return\non account performance',
       main = rtnmain[i])
  for (x in 2:length(nrolls)){
    lines(cal, temp %>% rollmean(nrolls[x], na.rm = T, align = 'right', fill = NA), col = cols[x])
    }
  legend('top', col = cols, legend = nrolls, lty = 1, title = 'Rolling window size (days)', horiz = T)
}


for (i in 1:NCOL(retcal)){
  temp = retcal[,i]
  plot(cal, temp %>% rollsum(7, na.rm = T, align = 'right', fill = NA), type = 'l', col = cols[1],
       ylim = c(-0.5,0.3),
       xlab = 'Calendar date',
       ylab = 'Log return on account performance\nover rolling window period',
       main = rtnmain[i])
  for (x in 2:length(nrolls)){
    lines(cal, temp %>% rollsum(nrolls[x], na.rm = T, align = 'right', fill = NA), col = cols[x])
    }
  legend('top', col = cols, legend = nrolls, lty = 1, title = 'Rolling window size (days)', horiz = T)
}
```  

```{r eval=F}
first_sell=function(date1,action1){
  options(warn = -1)
  y=date1[action1=='S']
  Mat=outer(date1,y,FUN=function(x,z){ifelse(z<x,Inf,z)})
  ind=apply(Mat,1,FUN=function(x){min(x)})
  return(as.Date(ind))
}

u.trans3=u.trans2[, list(qty_trans=sum(qty_trans),vol_chf_trans=sum(vol_chf_trans)), by=c('client','date_trans','action','security_key')]

setkey(u.trans3, "client") #used for .(x) later
registerDoMC(cores=15)
u.trans_match = foreach(x=unique(u.trans3[action == 'B',client]), .combine="rbind") %dopar%
           u.trans3[.(x), list(
             client, date_trans, action, qty_trans, vol_chf_trans,
             sell_date = first_sell(date_trans, action)), by = security_key]

save(u.trans_match, file = 'u.trans_match.rda')
```  
  
```{r eval=F}
load('u.trans_match.rda')
load('regtable.rda')

u.trans_match = u.trans_match[,price_chf := vol_chf_trans/qty_trans]

inscope = sty[,c('sec_id','security_key')] %>% unique %>%
  merge(u.trans_match[,c('client','security_key')] %>% unique)

u.trans_sell = u.trans_match[action == 'S', !'date_trans']

u.trans_matched = u.trans_match[action == 'B'] %>% 
  merge(u.trans_sell[, action := NULL], suffixes = c(".buy",".sell"),
        by =  c('security_key','client','sell_date'), all.x=T)

regtable$firstobs %<>% as.Date
u.trans_matched = merge(u.trans_matched, regtable[,c('client', 'firstobs')], by = 'client')

u.trans_matched[, ':='(age = (date_trans - firstobs) %>% as.numeric,
                       profit = price_chf.sell/price_chf.buy -1)]
```  
  
```{r profitlikelihood, eval=F}
thresh = 0.00
temp = u.trans_matched[
   , ':='(n = sum(is.finite(profit)), succount = sum(profit > thresh, na.rm = T)), by = age][,c('age', 'n', 'succount')] %>% unique
temp = temp[order(age)]

for (nroll in nrolls){ # size of rolling window
  temp[, paste0('ma', nroll) := rollsum(
    succount, nroll, na.rm = T, align = 'right', fill = NA)/rollsum(
    n, nroll, na.rm = T, align = 'right', fill = NA)]
}

 with(plot(age, get('ma7'), type = 'l', col = cols[1],
       xlab = 'Trading age (days)',
       ylab = 'Success likelihood',
       ylim = c(0.56, 0.69)
       ),
       data = temp)
  
  for (x in 2:length(nrolls)){
    with(lines(age, get(paste0('ma',nrolls[x])), col = cols[x]), data = temp)
  }
  legend('top', col = cols, legend = nrolls, lty = 1, title = 'Rolling window size (days)', horiz = T)
  

```  

```{r profit, eval=F}
temp = u.trans_matched[profit<quantile(profit,0.999, na.rm = T)][, ':='(n = sum(is.finite(profit)), profit = sum(profit)), by = age][,c('age', 'n', 'profit')] %>% unique

temp = temp[order(age)]

for (nroll in nrolls){ # size of rolling window
  temp[, paste0('ma', nroll) := rollsum(
    profit, nroll, na.rm = T, align = 'right', fill = NA)/rollsum(
    n, nroll, na.rm = T, align = 'right', fill = NA)]
}

 with(plot(age, get('ma7'), type = 'l', col = cols[1],
       xlab = 'Trading age (days)',
       ylab = 'Average profitability per age',
       ylim = c(0, 0.1)
       ),
       data = temp)
  
  for (x in 2:length(nrolls)){
    with(lines(age, get(paste0('ma',nrolls[x])), col = cols[x]), data = temp)
  }
  legend('top', col = cols, legend = nrolls, lty = 1, title = 'Rolling window size (days)', horiz = T)
  

selectyear = 2015
temp = u.trans_matched[profit<quantile(profit,0.999, na.rm = T) & format(date_trans, '%Y') == selectyear
                       ][, ':='(n = sum(is.finite(profit)), profit = sum(profit)), by = age][,c('age', 'n', 'profit')] %>% unique

temp = temp[order(age)]

for (nroll in nrolls){ # size of rolling window
  temp[, paste0('ma', nroll) := rollsum(
    profit, nroll, na.rm = T, align = 'right', fill = NA)/rollsum(
    n, nroll, na.rm = T, align = 'right', fill = NA)]
}

 with(plot(age, get('ma7'), type = 'l', col = cols[1],
       xlab = 'Trading age (days)',
       ylab = 'Average profitability per age',
       ylim = c(0.02, 0.16)
       ),
       data = temp)
  
  for (x in 2:length(nrolls)){
    with(lines(age, get(paste0('ma',nrolls[x])), col = cols[x]), data = temp)
  }
  legend('top', col = cols, legend = nrolls, lty = 1, title = 'Rolling window size (days)', horiz = T)
```

```{r survcurvedef1, include = F, eval = F, echo = F}
  svft = survfit(Surv(time=lifetime, event=uncensored) ~ 1, 
                 data = regtable[
                   format(firstobs, "%Y") <= ctryr$max & format(lastobs, "%Y") >= ctryr$min
                   ])
  
  nrisk = svft[['n.risk']] 
  trint1$nrisk = approx(x = svft[['time']][nrisk>4000] - 0.25, y = nrisk[nrisk>4000],
         xout = trint1$age)$y
  
  
 
  plot(svft[['time']], svft[['n.risk']],  col = 'red')
  lines(trint1$age, trint1$nrisk)



svft = survfit(Surv(time=lifetime, event=uncensored) ~ title_label, data = regtable)
plot(svft, xaxs ='i', ylim = c(0,1), yaxs ='i', conf.int = F,
     xlab = 'Trading experience since first trade (days)', ylab = 'survival rate')


plot(survfit(Surv(
  time=lifetime, event=uncensored
  ) ~ title_label + TradesOptions, data = regtable),
     xlim = c(0,6250), xaxs ='i', ylim = c(0,1), yaxs ='i', conf.int = F,
     xlab = 'Trading experience since first trade (days)', ylab = 'survival rate')

```

```{r survcurveemp, include = F, eval = F, echo = F}
load('u.trans3.rda')
clientdaily = readRDS('clientdaily.Rds')

regtable[, ':='(uncensored = ifelse(is.na(closing_date), 0,1), 
                lastobs = ifelse(is.na(closing_date), last_tr,closing_date) %>% as.Date,
                TradesOptions = as.numeric(client %in% optiontaders))][, ':='(
                lifetime = difftime(lastobs, firstobs, units = 'days')+0.25,
                enterage = as.numeric(format(first_tr,'%Y')) - actualby
                )]

# define subset of cohorts for survival plot
subsets = list(
  Aggregated = 1:NROW(regtable),
  EnterBefore2008 = which(as.numeric(format(regtable$first_tr,'%Y')) < 2008),
  EnterFrom2008To2010 = which(as.numeric(format(regtable$first_tr,'%Y')) >= 2008 & as.numeric(format(regtable$first_tr,'%Y')) <= 2010),
  EnterAfter2010 = which(as.numeric(format(regtable$first_tr,'%Y')) > 2010),
  EnterAgeBelow34 = which(regtable$enterage < 34),
  EnterAgeFrom34To45 = which(regtable$enterage >= 34 & regtable$enterage <= 45),
  EnterAgeAbove45 = which(regtable$enterage > 45),
  OptionTrader = which(regtable$TradesOptions ==1),
  NonOptionTrader = which(regtable$TradesOptions !=1),
  Women = which(regtable$gender),
  Men = which(!regtable$gender)
)

for (i in 1:length(subsets)){
surtbl = regtable[subsets[[i]],]
clientsurv = with(surtbl, Surv(lifetime,uncensored))

par(bty = 'l')

cssum = as.data.frame(summary(survfit(clientsurv ~ 1
                              )))[c(
  "time", "n.risk", "n.event", "surv", "std.err", "lower", "upper"
  )])

# coxph(Surv(lifetime,uncensored) ~ Rit60wt+smiret,data = surtbl)
# temp = glm(Surv ~ Rit60wt + smiret,data = surtbl, family = binomial(link = "probit"))
surtbl %<>% transform(mf = as.numeric(as.factor(title_label)))
xlimax = rev(cssum$time)[4]
# plot(clientsurv~1,
plot(survfit(Surv(lifetime,uncensored) ~ title_label, data = surtbl),
     ylim = c(0,1), xlim = c(0,xlimax),xaxs ='i', yaxs ='i', conf.int = F,
     xlab = 'Trading experience since first trade (days)', ylab = 'survival rate')

# plot(survfit(Surv(lifetime,uncensored) ~ 1, data = surtbl),
#      ylim = c(0,1), xlim = c(0,xlimax),xaxs ='i', yaxs ='i', conf.int = F,
#                     xlab = 'Trading experience since first trade (days)', ylab = 'survival rate')


nlag = 60
cssum$slope = c(rep(NA,nlag/2), diff(cssum$surv,lag=nlag)/diff(cssum$time,lag=nlag), rep(NA,nlag/2))
cssum$intercept = cssum$surv - cssum$slope*cssum$time
cssum = cssum[-NROW(cssum)+(0:1),]

abline(h=0.5, col = 'red',lwd = 0.5)

avgrate = (min(cssum$surv)-1)/max(cssum$time)
abline(a=1, b=avgrate, col = 'blue')
temp = which.max(cssum$slope)

linelen = xlimax/10
segments(x0=cssum$time[temp] - linelen, y0 = cssum$surv[temp] - linelen * cssum$slope[temp], 
        x1 = cssum$time[temp] + linelen, y1 = cssum$surv[temp] + linelen * cssum$slope[temp],
        col = 'violet')

text(labels = paste0('experience: ',cssum$time[temp], ' days\nexit rate: ', round(100*cssum$slope[temp],4), '% / day'),
     x=cssum$time[temp]+1050, y = cssum$surv[temp], adj = c(0,0), xpd = T)

temp = which.min(cssum$slope)
segments(x0=cssum$time[temp] - linelen, y0 = cssum$surv[temp] - linelen * cssum$slope[temp], 
        x1 = cssum$time[temp] + linelen, y1 = cssum$surv[temp] + linelen * cssum$slope[temp],
        col = 'violet')

text(labels = paste0('experience: ',cssum$time[temp], ' days\nexit rate: ', round(100*cssum$slope[temp],4), '% / day'),
     x=cssum$time[temp], y = cssum$surv[temp], adj = c(1,1))

legend('topright', legend = paste0(names(subsets)[i], '\n# obs: ',NROW(surtbl)), bty = 'n', text.col = 'grey30', cex = 1.2)
legend('bottomleft', legend = c(
  '90% confidence interval', 'empirical survival', paste0(
    'average exit rate\n(age 0 - ', max(cssum$time), ' days): ', round(100*avgrate,4), '% / day'
    )), lty = c(2,1,1), col = c('black','black','blue'),bty = 'n'
)
}

```

```{r tradingintensitybyage, eval=F}
TradingIntensityAge = vector("list", length = NROW(ctryrs))

for (y in 1:NROW(ctryrs)){ # control for financial crisis
  
  ctryr = ctryrs[y,]
  
  temp0 = trint[format(date_trans, "%Y") >= ctryr$min & format(date_trans, "%Y") <= ctryr$max]
  
  temp2 = regtable[format(firstobs , "%Y") <= ctryr$max & format(lastobs, "%Y") >= ctryr$min, c('client', 'firstobs', 'lastobs', 'lifetime')]
  
  
  TradingIntensityAge[[y]]$ctryr = ctryr
  TradingIntensityAge[[y]]$bs = vector("list", length = NROW(bs))
  
  svft = survfit(Surv(time=lifetime, event=uncensored) ~ 1, data = regtable[
    format(firstobs, "%Y") <= ctryr$max & format(lastobs, "%Y") >= ctryr$min
    ])
  
  for (sel in 1:NROW(bs)){
  temp1 = temp0[grepl(bs[sel], action)]
  
  trint1 = temp1
  trint1[, ':='(
    N = .N,
    vol = sum(vol_chf_trans, na.rm = T)), by = 'age']
  
  trint1 = trint1[order(age), c('age','N', 'vol')] %>% unique
  
  nrisk = svft[['n.risk']] 
  trint1$nrisk = approx(x = svft[['time']][nrisk] - 0.25, y = nrisk[nrisk],
         xout = trint1$age)$y
  
  trint.ma = merge(data.table(age = 0:max(trint1$age)), trint1, all.x = T)
  
  for (nroll in nrolls){ # size of rolling window

    trint.ma[, paste0('ra', nroll,'nrisk') := rollsum(
        nrisk, nroll, na.rm = T, align = 'right', fill = NA)]
    
    trint.ma[, paste0('ra', nroll,'n') := rollsum(
      N, nroll, na.rm = T, align = 'right', fill = NA)]
    
    trint.ma[, paste0('ra', nroll,'vol') := rollsum(
      vol, nroll, na.rm = T, align = 'right', fill = NA)]
    
        
    trint.ma[[paste0('ra', nroll,'uniqttl')]] = sapply(
      trint.ma$age - (nroll-1)/2, function(i) sum(temp2$lifetime >= i, na.rm = T))
    
    temp = temp1[order(age),c('age', 'client', 'date_trans')] %>% unique
    
    trint.ma[[paste0('ra', nroll,'uniq')]] = rollapply(
      trint.ma$age, nroll, function(i) uniqueN(temp[age %between% range(i),client]),
      align = 'right', fill = NA)
  }
  
  TradingIntensityAge[[y]][['bs']][[sel]] = trint.ma
}
}

save(TradingIntensityAge, file = 'TradingIntensityAge.rda')
```

```{r tradingintensitybydate, eval=F}

temp0 = data.table(date_trans = 
                          (min(u.trans2$date_trans):max(u.trans2$date_trans)) %>% as.Date)
temp0$nrisk = sapply(
      temp0$date_trans, function(i) sum(
        regtable$firstobs <=  i & regtable$lastobs >= i))

temp2 = regtable[, c('client', 'firstobs', 'lastobs', 'lifetime')]

TradingIntensityDate = vector("list", length = NROW(bs))

for (sel in 1:NROW(bs)){
  temp1 = trint[grep(bs[sel], action)]
  
  trint1 = temp1
  
  trint1[, ':='(
    N = .N,
    vol = sum(vol_chf_trans, na.rm = T)), by = 'date_trans']
  
  trint1 = trint1[order(date_trans), c('date_trans','N', 'vol')] %>% unique %>% merge(temp0)
  
  trint.ma = merge(data.table(date_trans = min(trint1$date_trans):max(trint1$date_trans)), 
                   trint1, all.x = T, by = 'date_trans')
  for (nroll in nrolls){ # size of rolling window
    
    trint.ma[, paste0('ra', nroll,'nrisk') := rollsum(
        nrisk, nroll, na.rm = T, align = 'right', fill = NA)]
    
    trint.ma[, paste0('ra', nroll,'n') := rollsum(
      N, nroll, na.rm = T, align = 'right', fill = NA)]
    
    trint.ma[, paste0('ra', nroll,'vol') := rollsum(
      vol, nroll, na.rm = T, align = 'right', fill = NA)]
    
    trint.ma[[paste0('ra', nroll,'uniqttl')]] = rollapply(
      trint.ma$date_trans, nroll, function(i) sum(
        temp2$firstobs <= max(i) & temp2$lastobs >= min(i), na.rm = T),
      align = 'right', fill = NA)
    
    temp = temp1[order(date_trans),c('age', 'client', 'date_trans')] %>% unique
    
    trint.ma[[paste0('ra', nroll,'uniq')]] = rollapply(
      trint.ma$date_trans, nroll, function(i) uniqueN(temp[date_trans %between% range(i),client]),
      align = 'right', fill = NA)
    
    print(nroll)
  }
  trint.ma$date_trans %<>% as.Date
  TradingIntensityDate[[sel]] = trint.ma
}

save(TradingIntensityDate, file = 'TradingIntensityDate.rda')
```

```{r tradingintensity, eval=F}
load('TradingIntensityAge.rda')
load('TradingIntensityDate.rda')

minage = 200
maxage = 5800 # TradingIntensityAge[[1]][['bs']][[3]]$age %>% max
maxn = 0.1
maxchf = 1700

bsttl = c('Buy trades only', 'Sell trades only', 'All (buy and sell) trades')

for (y in 1:NROW(ctryrs)){ # control for financial crisis
  for (sel in 1:NROW(bs)){
    
  trint.ma = TradingIntensityAge[[y]][['bs']][[sel]]
  
  # number
  with(plot(age, get('ra7n')/get('ra7nrisk'), type = 'l', col = cols[1],
       xlab = 'Trading age (days)',
       ylab = 'Daily trading intensity\n(No. trades / day / active trader)',
       xlim = c(minage, maxage),
       ylim = c(0, maxn),
       main = paste0(bsttl[sel], ', ', ctryrs$min[y], '--', ctryrs$max[y])),
       data = trint.ma)
  
  for (x in 2:length(nrolls)){
    with(lines(age, get(paste0('ra',nrolls[x], 'n'))/get(paste0('ra',nrolls[x], 'nrisk')), col = cols[x]), data = trint.ma)
  }
  legend('top', col = cols, legend = nrolls, lty = 1, title = 'Rolling window size (days)', horiz = T)
  
  # volume
  with(plot(age, get('ra7vol')/get('ra7nrisk'), type = 'l', col = cols[1],
       xlab = 'Trading age (days)',
       ylab = 'Daily trading intensity\n(Volume (CHF) / day / active trader)',
       xlim = c(minage, maxage),
       ylim = c(0, maxchf),
       main = paste0(bsttl[sel], ', ', ctryrs$min[y], '--', ctryrs$max[y])),
       data = trint.ma)
  
  for (x in 2:length(nrolls)){
    with(lines(age, get(paste0('ra',nrolls[x], 'vol'))/get(paste0('ra',nrolls[x], 'nrisk')), col = cols[x]), data = trint.ma)
  }
  legend('top', col = cols, legend = nrolls, lty = 1, title = 'Rolling window size (days)', horiz = T)
  
  # Likelihood
  with(plot(age, get('ra7uniq')/get('ra7uniqttl'), type = 'l', col = cols[1],
       xlab = 'Trading age (days)',
       ylab = 'Trading likelihood within window\n(No. traders that traded / No. total active traders)',
       xlim = c(minage, maxage),
       ylim = c(0, 1),
       main = paste0(bsttl[sel], ', ', ctryrs$min[y], '--', ctryrs$max[y])),
       data = trint.ma)
  
  for (x in 2:length(nrolls)){
    with(lines(age, get(paste0('ra',nrolls[x], 'uniq'))/get(paste0('ra',nrolls[x], 'uniqttl')), col = cols[x]), data = trint.ma)
  }
  legend('top', col = cols, legend = nrolls, lty = 1, title = 'Rolling window size (days)', horiz = T)
  }
}

for (sel in 1:NROW(bs)){
  trint.ma = TradingIntensityDate[[sel]]
  
  # number
  with(plot(date_trans, get('ra7n')/get('ra7nrisk'), type = 'l', col = cols[1],
       xlab = 'Calender date',
       ylab = 'Daily trading intensity\n(No. trades / day / active trader)',
       ylim = c(0, maxn),
       main = bsttl[sel]),
       data = trint.ma)
  
  
  for (x in 2:length(nrolls)){
    with(lines(date_trans, get(paste0('ra',nrolls[x], 'n'))/get(paste0('ra',nrolls[x], 'nrisk')), col = cols[x]), data = trint.ma)
  }
  legend('top', col = cols, legend = nrolls, lty = 1, title = 'Rolling window size (days)', horiz = T)
  
  
  # volume
  with(plot(date_trans, get('ra7vol')/get('ra7nrisk'), type = 'l', col = cols[1],
       xlab = 'Calender date',
       ylab = 'Daily trading intensity\n(No. trades / day / active trader)',
       ylim = c(0, maxchf),
       main = bsttl[sel]),
       data = trint.ma)
  
  for (x in 2:length(nrolls)){
    with(lines(date_trans, get(paste0('ra',nrolls[x], 'vol'))/get(paste0('ra',nrolls[x], 'nrisk')), col = cols[x]), data = trint.ma)
  }
  legend('top', col = cols, legend = nrolls, lty = 1, title = 'Rolling window size (days)', horiz = T)

  # Likelihood
  with(plot(date_trans, get('ra7uniq')/get('ra7uniqttl'), type = 'l', col = cols[1],
       xlab = 'Calender date',
       ylab = 'Trading likelihood within window\n(No. traders that traded / No. total active traders)',
       ylim = c(0, 1),
       main = bsttl[sel]),
       data = trint.ma)
  
  for (x in 2:length(nrolls)){
    with(lines(date_trans, get(paste0('ra',nrolls[x], 'uniq'))/get(paste0('ra',nrolls[x], 'uniqttl')), col = cols[x]), data = trint.ma)
  }
  legend('top', col = cols, legend = nrolls, lty = 1, title = 'Rolling window size (days)', horiz = T)
}

``` 
  
```{r dailymatrix, eval=F}
load('regtable.rda')
load('clientdaily.rda')
# Takes forever
clientdaily_matrixa = dcast(clientdaily[,c('client','age', 'daily_perf')], client ~ age, value.var = 'daily_perf')
clientdaily_excs_matrixa = dcast(clientdaily, client ~ age, value.var = 'daily_perf_excess')


clientdaily_matrix = dcast(clientdaily, client ~ account_date, value.var = 'daily_perf')
clientdaily_excs_matrix = dcast(clientdaily, client ~ account_date, value.var = 'daily_perf_excess')


retcala = cbind(colMeans(clientdaily_matrixa[, -1], na.rm=T),
               colMeans(clientdaily_excs_matrixa[, -1], na.rm=T))

retcal = cbind(colMeans(clientdaily_matrix[, -1], na.rm=T),
               colMeans(clientdaily_excs_matrix[, -1], na.rm=T))

save(retcala, retcal, file = 'retcal.rda')

```  

```{r returndist, eval=F}
gc()

# if(!exists('clientdaily')){load('clientdaily.rda')}

if(!(exists('clientdaily2')|exists('clientdaily'))){
  load('clientdaily2.rda')
  clientdaily = clientdaily2
  rm(clientdaily2)}

par(mgp=c(1.5,0.5,0), xpd = F)

rselect = 'lastr'
ageselect = 'maxage'

# for (i in 0:length(lbls)){
for (ex in 1:2){
  for (i in 1:4){
  gc()
    indtemp = get(paste0('ind',i))
    if (ex==2){indtemp = indtemp & ind12}
    
    lbl = lbls[i]
    if (ex==2){lbl = paste0(lbl, '\nExit')}
  
  temp = clientdaily[indtemp, list(
  avgage = mean(age, na.rm = T), maxage = max(age, na.rm = T),
  avgr = mean(raprofit365, na.rm = T), lastr = tail(raprofit365, 1),
  exit = sum(exitpoint, na.rm = T)
  ), by = client][get(rselect) %>% is.finite]
  
  agequants = temp[[ageselect]] %>% quantile(c(1/5, 4/5))
  
  indtemp1 = (temp[[ageselect]] >= agequants[2]) %>% which
  indtemp2 = (temp[[ageselect]] <= agequants[1]) %>% which
  
  series1 = temp[[rselect]][indtemp1]
  series2 = temp[[rselect]][indtemp2]
  
  series3 = temp[[rselect]][-c(indtemp1, indtemp2)]


s3 = series3 %>% density(na.rm = T, n=19999) 
  
s1 = series1 %>% density(na.rm = T, n=19999) 

s2 = series2 %>% density(na.rm = T, n=19999)


s1 %>% plot(xlim=c(-1,1), main = '', 
            xlab = paste0('361-day return'), ylim = c(0, max(s1$y, s2$y, s3$y) * 1.01), yaxs='i', bty = 'l')
s2 %>% lines(col='red')
# s3 %>% lines(col='blue')


legend('topright', legend = 'Age highest 20\\%',
       lty = 1, col = 'black', xpd = T, bty = 'n', cex = 0.8)
legend('topright', legend = textlabel(series1 %>% na.omit), bty='n', cex = 0.8)

legend('topleft', legend = 'Age lowest 20\\%',
       lty = 1, col = 'red', xpd = T, bty = 'n', cex = 0.8)
legend('topleft', legend = textlabel(series2 %>% na.omit), bty='n', cex = 0.8)

p = ks.test(series1, series2)$p
p2 = t.test(series1, series2, na.action=na.omit, alternative = 'two.sided', mu = 0, paired = F, conf.level = 0.95)$p.value

cortest = cor.test(as.numeric(temp[[ageselect]]), temp[[rselect]])

mtext(paste0('KS-test: $p=',formatC(p, digits = 3, format = 'f'),'$',funcstar(p),
             '\nt-test: $p=',formatC(p2, digits = 3, format = 'f'),'$',funcstar(p2),
             '\nCorr($t$, $R$): ', round(cortest$estimate, 3), funcstar(cortest$p.value)
             ),side=3, line = 0, cex = 1)

mtext(lbl,side=1, line = 4, cex = 1)
}
}
```  
